import { readFileSync, writeFileSync } from "fs";

const existing = JSON.parse(readFileSync("content/deathmatch-matchups.json", "utf-8"));

const batch7 = [
  {
    slug: "mcqueen-vs-newman",
    fighter_a_name: "Steve McQueen",
    fighter_b_name: "Paul Newman",
    fighter_a_nickname: "The King of Cool",
    fighter_b_nickname: "Cool Hand Luke",
    tagline: "The King of Cool vs The Blue Eyes",
    matchup_type: "rivalry",
    difficulty: 2,
    rounds: [
      { round_number: 1, round_label: "THE BILLING", question_text: "When these two starred in The Towering Inferno (1974), one of them demanded equal billing, equal lines, AND the last line of the movie. Their names were displayed diagonally on the poster so neither appeared \"above\" the other. Who made the demands?", correct_answer: "a", explanation: "Steve McQueen was obsessively competitive with Newman. He counted lines in the script and demanded the final line in the film regardless of whether it made narrative sense. Newman called him \"chicken s--t.\"", fun_fact: "The diagonal billing was a Hollywood first \u2014 McQueen's name was positioned lower-left, Newman upper-right, so both could claim top billing." },
      { round_number: 2, round_label: "THE SALAD", question_text: "One of them founded a food company whose products have generated over $600 million for children's charities \u2014 starting with a homemade salad dressing. Which one?", correct_answer: "b", explanation: "Paul Newman founded Newman's Own in 1982 with author A.E. Hotchner, starting with salad dressing they'd been giving to friends. The company donates 100% of after-tax profits to charity.", fun_fact: "They launched with $40,000 combined. Newman said: \"The embarrassing thing is that the salad dressing is outgrossing my films.\"" },
      { round_number: 3, round_label: "THE MACHINE", question_text: "One of them was so obsessed with racing that he competed in the 12 Hours of Sebring, nearly entered Le Mans, and made an entire movie about the race as a passion project. Which one?", correct_answer: "a", explanation: "Steve McQueen was a serious racing driver who competed professionally. His 1971 film Le Mans was a passion project that nearly bankrupted the studio. He said: \"Racing is life. Anything before or after is just waiting.\"", fun_fact: "He often raced under the fake name \"Harvey Mushman\" to avoid attention from studios who banned him from racing." },
      { round_number: 4, round_label: "THE RACER TOO", question_text: "One of them also raced cars professionally \u2014 finishing second at the 24 Hours of Le Mans at age 70. Which one?", correct_answer: "b", explanation: "Paul Newman was also a serious racing driver. He finished second in class at the 1979 24 Hours of Le Mans and continued racing into his 80s. He won four national championships with the Sports Car Club of America.", fun_fact: "Both were elite racing drivers. This is the only Hollywood rivalry where both men could actually beat you on a racetrack." },
      { round_number: 5, round_label: "THE ESCAPE", question_text: "One of them starred in The Great Escape (1963), doing many of his own motorcycle stunts in one of cinema's most famous chase sequences. Which one?", correct_answer: "a", explanation: "Steve McQueen played Captain Hilts in The Great Escape. The iconic motorcycle jump attempt at the Swiss border fence became one of the most famous stunts in film history.", fun_fact: "McQueen actually did most of the riding himself, but the final fence jump was performed by his friend Bud Ekins." },
      { round_number: 6, round_label: "THE COOL", question_text: "One of them starred in a 1967 film as a defiant prisoner who refuses to break, delivering the line: \"What we've got here is failure to communicate.\" Which one?", correct_answer: "b", explanation: "Paul Newman starred in Cool Hand Luke (1967), playing a rebellious prisoner in a Florida chain gang. The film's famous line was delivered by the Captain (Strother Martin), not Newman's character.", fun_fact: "Newman was nominated for the Oscar but lost. The egg-eating contest scene \u2014 50 hard-boiled eggs in one hour \u2014 is one of the most iconic scenes in American cinema." },
      { round_number: 7, round_label: "THE END", question_text: "One of them died at 50, the other lived to 83. Who died young?", correct_answer: "a", explanation: "Steve McQueen died on November 7, 1980, at age 50, from mesothelioma (a cancer linked to asbestos exposure). Paul Newman died on September 26, 2008, at age 83, from lung cancer.", fun_fact: "McQueen was the highest-paid movie star in the world at the time of his death. Newman spent his final decades racing cars and giving away hundreds of millions to charity." }
    ]
  },
  {
    slug: "pfeiffer-vs-fawcett",
    fighter_a_name: "Michelle Pfeiffer",
    fighter_b_name: "Farrah Fawcett",
    fighter_a_nickname: "Catwoman",
    fighter_b_nickname: "The Poster",
    tagline: "Catwoman vs The Poster",
    matchup_type: "rivalry",
    difficulty: 2,
    rounds: [
      { round_number: 1, round_label: "THE POSTER", question_text: "One of them had a red swimsuit poster that sold 12 million copies \u2014 the best-selling poster in history. Which one?", correct_answer: "b", explanation: "Farrah Fawcett's 1976 red swimsuit poster sold 12 million copies, making it the best-selling poster of all time. It became a cultural icon of the late 1970s.", fun_fact: "She earned just $15,000 for the photo shoot. The poster outsold every poster before or since." },
      { round_number: 2, round_label: "THE CAT", question_text: "One of them played Catwoman in a Tim Burton film \u2014 a performance widely considered the definitive portrayal of the character. Which one?", correct_answer: "a", explanation: "Michelle Pfeiffer played Selina Kyle / Catwoman in Batman Returns (1992). Her performance is still regarded as the greatest portrayal of Catwoman in any medium.", fun_fact: "She learned to crack a bullwhip for the role and did many of her own stunts in the latex catsuit." },
      { round_number: 3, round_label: "THE ANGELS", question_text: "One of them became a global phenomenon through a TV show about three female private detectives \u2014 but quit after just one season. Which one?", correct_answer: "b", explanation: "Farrah Fawcett starred in Charlie's Angels (1976) but left after the first season, feeling creatively stifled. Her departure made headlines worldwide and led to a lawsuit from the production company.", fun_fact: "She returned as a guest star in six episodes across seasons 3 and 4 as part of a legal settlement." },
      { round_number: 4, round_label: "THE SCARFACE", question_text: "One of them played Elvira Hancock opposite Al Pacino in Scarface (1983) \u2014 a breakout role that launched her film career. Which one?", correct_answer: "a", explanation: "Michelle Pfeiffer played Elvira, Tony Montana's icy wife, in Brian De Palma's Scarface. The role established her as a serious film actress beyond her beauty.", fun_fact: "She was terrified during filming. She later said she had no idea what she was doing and was intimidated by Pacino." },
      { round_number: 5, round_label: "THE HAIR", question_text: "One of them had a feathered hairstyle so influential that millions of women brought her photo to salons \u2014 the \"feathered look\" became the defining hairstyle of the late 1970s. Which one?", correct_answer: "b", explanation: "Farrah Fawcett's feathered, blown-back hairstyle became the most copied hairstyle of the 1970s. Her hairdresser Allen Edwards created the look using layers and a blow dryer.", fun_fact: "The hairstyle is still known simply as \"The Farrah\" \u2014 no last name needed." },
      { round_number: 6, round_label: "THE RANGE", question_text: "One of them earned three Oscar nominations across three decades \u2014 for Dangerous Liaisons (1988), The Fabulous Baker Boys (1989), and Love Field (1992). Which one?", correct_answer: "a", explanation: "Michelle Pfeiffer received three Best Actress/Supporting Actress nominations in four years, proving extraordinary range from period drama to musical romance to racial drama.", fun_fact: "She never won the Oscar. Many consider her the most talented actress of her generation to be shut out." },
      { round_number: 7, round_label: "THE FAREWELL", question_text: "One of them died on the same day as Michael Jackson \u2014 June 25, 2009 \u2014 with her death overshadowed by the global coverage of his. Which one?", correct_answer: "b", explanation: "Farrah Fawcett died of anal cancer on the morning of June 25, 2009, at age 62. Hours later, Michael Jackson died of cardiac arrest, dominating the news cycle and eclipsing her death.", fun_fact: "Her documentary Farrah's Story, about her cancer battle, had been watched by 9 million viewers just weeks earlier." }
    ]
  },
  {
    slug: "winehouse-vs-badu",
    fighter_a_name: "Amy Winehouse",
    fighter_b_name: "Erykah Badu",
    fighter_a_nickname: "The Lioness",
    fighter_b_nickname: "The Queen of Neo-Soul",
    tagline: "Soul Burned vs Soul Eternal",
    matchup_type: "crossover",
    difficulty: 3,
    rounds: [
      { round_number: 1, round_label: "THE ALBUM", question_text: "One of them released Back to Black (2006) \u2014 an album that sold over 20 million copies and is considered one of the greatest records of the 21st century. Which one?", correct_answer: "a", explanation: "Amy Winehouse's Back to Black won five Grammy Awards and revived interest in classic soul, jazz, and girl-group production. It remains one of the best-selling albums in UK history.", fun_fact: "She wrote most of it about her toxic on-off relationship with Blake Fielder-Civil, whom she later married." },
      { round_number: 2, round_label: "THE MOVEMENT", question_text: "One of them is credited with launching the entire neo-soul genre \u2014 her 1997 debut album placed her at the forefront of a movement that redefined R&B. Which one?", correct_answer: "b", explanation: "Erykah Badu's Baduizm (1997) is widely considered the album that launched neo-soul. Music critics dubbed her the \"Queen of Neo-Soul\" and the \"First Lady of Neo-Soul.\"", fun_fact: "Her career began after opening for D'Angelo in 1994 in Fort Worth, Texas." },
      { round_number: 3, round_label: "THE 27 CLUB", question_text: "One of them died at age 27 from alcohol poisoning \u2014 joining the tragic \"27 Club\" alongside Jimi Hendrix, Jim Morrison, and Kurt Cobain. Which one?", correct_answer: "a", explanation: "Amy Winehouse died on July 23, 2011, in London. Her blood alcohol level was more than five times the legal drink-drive limit. She was 27.", fun_fact: "Her father Mitch said she had told him three weeks earlier that she had stopped drinking. The relapse was fatal." },
      { round_number: 4, round_label: "THE HEAD WRAP", question_text: "One of them is as famous for her towering head wraps and Afrocentric style as for her music \u2014 using fashion as a form of spiritual and cultural expression. Which one?", correct_answer: "b", explanation: "Erykah Badu's head wraps became her visual trademark, representing her connection to African heritage, spirituality, and self-expression. They are inseparable from her artistic identity.", fun_fact: "She has said the wraps represent her \"queendom\" and her refusal to conform to Western beauty standards." },
      { round_number: 5, round_label: "THE GRAMMYS", question_text: "One of them won five Grammy Awards in a single night \u2014 the most by a British artist at that time. Which one?", correct_answer: "a", explanation: "Amy Winehouse won five Grammys at the 2008 ceremony for Back to Black, including Record of the Year, Song of the Year, and Best New Artist. She couldn't attend in person because her US visa was denied.", fun_fact: "She performed via satellite from London. She looked stunned when her name was called \u2014 genuinely shocked." },
      { round_number: 6, round_label: "THE LIVE EXPERIENCE", question_text: "One of them is known for concerts that can last 4+ hours, blending music with spiritual ceremony, comedy, and audience communion \u2014 no two shows are ever alike. Which one?", correct_answer: "b", explanation: "Erykah Badu's live shows are legendary for their length and unpredictability. She improvises extensively, incorporates spirituality and humor, and often turns concerts into communal experiences.", fun_fact: "She has been actively performing for over 25 years and continues to sell out venues worldwide." },
      { round_number: 7, round_label: "THE SONG", question_text: "One of them sang \"They tried to make me go to rehab, I said no, no, no\" \u2014 a lyric that became tragically prophetic. Which one?", correct_answer: "a", explanation: "Amy Winehouse's \"Rehab\" (2006) was based on her real refusal to attend rehab at the urging of her management. The song won three Grammys. She died of alcohol-related causes five years later.", fun_fact: "The song was written in its entirety in just a few hours. Mark Ronson produced it to sound like a 1960s Motown record." }
    ]
  },
  {
    slug: "bias-vs-ewing",
    fighter_a_name: "Len Bias",
    fighter_b_name: "Patrick Ewing",
    fighter_a_nickname: "The Fallen Star",
    fighter_b_nickname: "The Tower",
    tagline: "The Tragedy vs The Tower",
    matchup_type: "era",
    difficulty: 3,
    rounds: [
      { round_number: 1, round_label: "THE PICK", question_text: "One of them was the #1 overall pick in the 1985 NBA Draft \u2014 a pick that was decided by the first-ever NBA Draft Lottery. Which one?", correct_answer: "b", explanation: "Patrick Ewing was selected first overall by the New York Knicks in 1985. The draft lottery was introduced that year specifically because teams were suspected of tanking to get a shot at Ewing.", fun_fact: "The Knicks won the lottery with a 1-in-7 chance. Conspiracy theories about a frozen envelope persist to this day." },
      { round_number: 2, round_label: "THE TRAGEDY", question_text: "One of them died of a cocaine overdose just two days after being selected #2 overall in the 1986 NBA Draft by the Boston Celtics. Which one?", correct_answer: "a", explanation: "Len Bias was picked second overall on June 17, 1986, and died on June 19 from cardiac arrhythmia caused by cocaine. He was 22 years old. It is considered the greatest \"what if\" in NBA history.", fun_fact: "His death directly led to the Anti-Drug Abuse Act of 1986, which introduced mandatory minimum sentences for drug offenses and reshaped US drug policy for decades." },
      { round_number: 3, round_label: "THE DYNASTY", question_text: "One of them was supposed to extend the Boston Celtics dynasty alongside Larry Bird \u2014 but never played a single NBA game. Which one?", correct_answer: "a", explanation: "Len Bias was drafted by the Celtics to be Larry Bird's successor. Had he played, the Celtics dynasty of the 1980s might have continued well into the 1990s. Instead, the franchise declined.", fun_fact: "Bird later said losing Bias was devastating: \"That was a turning point for our franchise.\"" },
      { round_number: 4, round_label: "THE WARRIOR", question_text: "One of them played 15 seasons for the New York Knicks, made 11 All-Star teams, and became the franchise's all-time leading scorer \u2014 but never won a championship. Which one?", correct_answer: "b", explanation: "Patrick Ewing spent 15 years with the Knicks, averaging 21 points and 9.8 rebounds. He made the NBA Finals in 1994 but lost to the Houston Rockets. He is the greatest player to never win a ring in Knicks history.", fun_fact: "He scored 24,815 career points. The only thing missing from his resume is a championship." },
      { round_number: 5, round_label: "THE COLLEGE", question_text: "One of them was the ACC Player of the Year at the University of Maryland and was considered the most exciting college player since Michael Jordan. Which one?", correct_answer: "a", explanation: "Len Bias was a two-time ACC Player of the Year at Maryland (1985, 1986). He averaged 23.2 points and 6.8 rebounds in his senior season. Scouts compared him directly to Michael Jordan.", fun_fact: "Jordan himself said Bias was one of the few players who could match him physically. They were built almost identically." },
      { round_number: 6, round_label: "THE OLYMPICS", question_text: "One of them won Olympic gold medals in 1984 and 1992 \u2014 the second time as part of the legendary \"Dream Team.\" Which one?", correct_answer: "b", explanation: "Patrick Ewing won gold at the 1984 Los Angeles Olympics and again at the 1992 Barcelona Olympics as a member of the Dream Team alongside Jordan, Bird, and Magic Johnson.", fun_fact: "The 1992 Dream Team is widely considered the greatest sports team ever assembled. They won every game by an average of 44 points." },
      { round_number: 7, round_label: "THE LAW", question_text: "One of them's death at 22 led directly to a federal law that introduced mandatory minimum sentences for drug offenses \u2014 reshaping American criminal justice for decades. Which one?", correct_answer: "a", explanation: "The Anti-Drug Abuse Act of 1986 was fast-tracked through Congress in the wake of Len Bias's death. It created the controversial 100-to-1 sentencing disparity between crack and powder cocaine.", fun_fact: "Legal scholars have called it one of the most consequential pieces of legislation in US history \u2014 all triggered by the death of a 22-year-old basketball player who never played a professional game." }
    ]
  },
  {
    slug: "hayes-vs-white",
    fighter_a_name: "Isaac Hayes",
    fighter_b_name: "Maurice White",
    fighter_a_nickname: "Black Moses",
    fighter_b_nickname: "The Maestro",
    tagline: "Shaft vs Earth, Wind & Fire",
    matchup_type: "rivalry",
    difficulty: 3,
    rounds: [
      { round_number: 1, round_label: "THE OSCAR", question_text: "One of them won the Academy Award for Best Original Song \u2014 becoming the first African American to win an Oscar in a non-acting category. Which one?", correct_answer: "a", explanation: "Isaac Hayes won the Oscar for \"Theme from Shaft\" at the 1972 ceremony. He performed the song shirtless and draped in gold chains on the Academy Awards stage.", fun_fact: "He beat out songs from Willy Wonka and Bedknobs and Broomsticks. The coolest man at the Oscars that night \u2014 by a mile." },
      { round_number: 2, round_label: "THE BAND", question_text: "One of them founded a band that blended funk, soul, jazz, R&B, pop, and African rhythms into something entirely new \u2014 eventually selling over 90 million records. Which one?", correct_answer: "b", explanation: "Maurice White founded Earth, Wind & Fire in 1969 in Chicago. The band's fusion of genres was revolutionary, and they became one of the best-selling bands in history with over 90 million records sold.", fun_fact: "The band's name comes from White's astrological chart \u2014 his sign had earth, air (wind), and fire as dominant elements. There's no water." },
      { round_number: 3, round_label: "THE VOICE", question_text: "One of them had a spoken-word voice so deep and distinctive that he became the voice of Chef on South Park for 14 seasons. Which one?", correct_answer: "a", explanation: "Isaac Hayes voiced Chef on South Park from 1997 to 2006. The character was beloved for his deep baritone and his habit of breaking into seductive songs. Hayes left the show over its satirization of Scientology.", fun_fact: "He was a practicing Scientologist. When South Park mocked the religion, he quit \u2014 despite years of the show mocking every other religion without complaint." },
      { round_number: 4, round_label: "THE DATE", question_text: "One of them wrote \"September\" \u2014 a song so universally joyful that it has become the most-played song at parties, weddings, and celebrations worldwide. Do you remember the 21st night of September? Which one?", correct_answer: "b", explanation: "Maurice White co-wrote \"September\" for Earth, Wind & Fire. Released in 1978, the song has become the definitive celebration anthem. It re-enters charts every September 21st.", fun_fact: "The songwriter who helped White write it asked why the date was the 21st. White said: \"It just sounded good. No other reason.\"" },
      { round_number: 5, round_label: "THE CHAINS", question_text: "One of them was as famous for his gold chains and shaved head as for his music \u2014 creating a visual image that influenced hip-hop fashion decades later. Which one?", correct_answer: "a", explanation: "Isaac Hayes's bald head and gold chains became his signature look. He performed at the Oscars draped in them. His visual style directly influenced the aesthetics of 1980s and 1990s hip-hop.", fun_fact: "He was nicknamed \"Black Moses\" \u2014 partly for his deep spiritual voice, partly because he looked like a god walking among mortals." },
      { round_number: 6, round_label: "THE KALIMBA", question_text: "One of them was a classically trained musician who played the kalimba (African thumb piano) as a signature element of the band's sound \u2014 bringing African instrumentation into mainstream pop. Which one?", correct_answer: "b", explanation: "Maurice White played the kalimba throughout Earth, Wind & Fire's career, making the African thumb piano a recognizable element of their sound. It connected the band's music to its African roots.", fun_fact: "He also played drums, percussion, and vocals. He was a multi-instrumentalist who studied at the Chicago Conservatory of Music." },
      { round_number: 7, round_label: "THE STAX", question_text: "One of them was a key songwriter and session musician at Stax Records in Memphis \u2014 helping craft the \"Memphis Soul\" sound that defined 1960s R&B alongside Otis Redding and Sam & Dave. Which one?", correct_answer: "a", explanation: "Isaac Hayes was a songwriter and session musician at Stax Records, co-writing hits like \"Soul Man\" and \"Hold On, I'm Comin'\" with David Porter for Sam & Dave. He helped build the Memphis soul sound.", fun_fact: "He didn't become a solo star until his late 20s. Before Shaft, he was the man behind the curtain \u2014 writing hits for everyone else." }
    ]
  }
];

const combined = [...existing, ...batch7];
writeFileSync("content/deathmatch-matchups.json", JSON.stringify(combined, null, 2));
console.log(`Total matchups: ${combined.length}`);
console.log("Added:", batch7.map(m => m.slug).join(", "));
