import { readFileSync, writeFileSync } from "fs";

const existing = JSON.parse(readFileSync("content/deathmatch-matchups.json", "utf-8"));

const batch4 = [
  {
    slug: "snoop-dogg-vs-dr-dre",
    fighter_a_name: "Snoop Dogg",
    fighter_b_name: "Dr. Dre",
    fighter_a_nickname: "The Doggfather",
    fighter_b_nickname: "The Architect",
    tagline: "The Prot\u00e9g\u00e9 vs The Architect",
    matchup_type: "rivalry",
    difficulty: 2,
    rounds: [
      { round_number: 1, round_label: "THE DISCOVERY", question_text: "One of them was discovered when his cousin handed a demo cassette tape to the other. Which one was discovered?", correct_answer: "a", explanation: "Snoop Dogg was introduced to Dr. Dre through Warren G, who gave Dre a cassette of Snoop's freestyle. Dre signed him immediately, and their first collaboration was the 1992 single \"Deep Cover.\"", fun_fact: "Warren G is Dr. Dre's step-brother. The whole thing was a family connection." },
      { round_number: 2, round_label: "THE ALBUM", question_text: "One of them produced The Chronic (1992) \u2014 the album that defined G-funk and West Coast hip-hop. Which one?", correct_answer: "b", explanation: "Dr. Dre produced and performed on The Chronic, featuring Snoop Dogg heavily. The album pioneered the G-funk sound \u2014 laid-back synths, deep bass, and melodic hooks over gangsta lyrics.", fun_fact: "Snoop appeared on so many tracks that people joked The Chronic was really a Snoop Dogg album with Dre producing." },
      { round_number: 3, round_label: "THE DEBUT", question_text: "One of them had a debut solo album that entered the Billboard 200 at number one with 806,000 copies sold in its first week. Which one?", correct_answer: "a", explanation: "Snoop Dogg's Doggystyle (1993) debuted at #1 with 806,000 first-week sales, a record at the time. It featured \"Gin and Juice\" and \"What's My Name?\"", fun_fact: "He recorded much of the album while facing a murder charge. He was acquitted in 1996." },
      { round_number: 4, round_label: "THE EMPIRE", question_text: "One of them co-founded Beats Electronics, which Apple bought for $3 billion in 2014 \u2014 making him hip-hop's first billionaire. Which one?", correct_answer: "b", explanation: "Dr. Dre co-founded Beats with Jimmy Iovine in 2008. Apple's $3 billion acquisition in 2014 made Dre the wealthiest figure in hip-hop history.", fun_fact: "Dre and Iovine both joined Apple's executive team after the sale." },
      { round_number: 5, round_label: "THE FRIENDSHIP", question_text: "One of them became best friends with Martha Stewart \u2014 co-hosting a cooking show, attending the Olympics together, and becoming one of America's most unlikely celebrity duos. Which one?", correct_answer: "a", explanation: "Snoop Dogg and Martha Stewart became friends after meeting on her show in 2008. They co-hosted Martha & Snoop's Potluck Dinner Party and attended the 2024 Paris Olympics together.", fun_fact: "Stewart once said Snoop brings \"a very different perspective to entertaining\" than she does. No kidding." },
      { round_number: 6, round_label: "THE MENTOR", question_text: "One of them discovered and launched the careers of Eminem, 50 Cent, and Kendrick Lamar \u2014 arguably the three biggest rappers of three consecutive decades. Which one?", correct_answer: "b", explanation: "Dr. Dre signed and produced debut albums for Eminem (1999), 50 Cent (2003), and Kendrick Lamar (2012). No other producer has launched three era-defining artists.", fun_fact: "He has only released three solo albums in 30+ years. His influence comes from producing others." },
      { round_number: 7, round_label: "THE REINVENTION", question_text: "One of them went from gangsta rapper to mainstream TV personality \u2014 coaching on The Voice, carrying the Olympic torch, and becoming a family-friendly brand. Which one?", correct_answer: "a", explanation: "Snoop Dogg became an NBC commentator for the 2024 Paris Olympics, has coached on The Voice, and carries the Olympic torch. His transformation from gangsta rap to wholesome entertainment icon is one of pop culture's greatest pivots.", fun_fact: "He also coaches youth football in Los Angeles. The league has produced multiple NFL players." }
    ]
  },
  {
    slug: "monroe-vs-andress",
    fighter_a_name: "Marilyn Monroe",
    fighter_b_name: "Ursula Andress",
    fighter_a_nickname: "The Blonde",
    fighter_b_nickname: "The Bond Girl",
    tagline: "Hollywood vs Bond",
    matchup_type: "era",
    difficulty: 2,
    rounds: [
      { round_number: 1, round_label: "THE NAME", question_text: "One of them was born Norma Jeane Mortenson and reinvented herself with a new name that became the most famous in Hollywood history. Which one?", correct_answer: "a", explanation: "Marilyn Monroe was born Norma Jeane Mortenson on June 1, 1926. She changed her name when she began modeling, taking her mother's maiden name Monroe and the first name Marilyn, suggested by a studio executive.", fun_fact: "She spent much of her childhood in foster homes and an orphanage before becoming the biggest movie star in the world." },
      { round_number: 2, round_label: "THE BIKINI", question_text: "One of them emerged from the Caribbean Sea in a white bikini in 1962 \u2014 creating one of the most iconic moments in cinema. The bikini later sold for $61,500 at auction. Which one?", correct_answer: "b", explanation: "Ursula Andress rose from the sea as Honey Ryder in Dr. No (1962), the first James Bond film. The white bikini with a diving knife became one of the most famous costumes in film history.", fun_fact: "She won the Golden Globe for New Star of the Year in 1964 for the role." },
      { round_number: 3, round_label: "THE SERENADE", question_text: "One of them sang \"Happy Birthday\" to the President of the United States in a dress so tight it had to be sewn onto her body. Which one?", correct_answer: "a", explanation: "Marilyn Monroe serenaded President John F. Kennedy on May 19, 1962, at Madison Square Garden. Her breathy, sexually charged rendition became legendary. The dress sold for $4.8 million at auction.", fun_fact: "She performed while running a 102-degree fever from a sinus infection." },
      { round_number: 4, round_label: "THE FRANCHISE", question_text: "One of them appeared in not one but two James Bond films \u2014 the first official one and a later parody. Which one?", correct_answer: "b", explanation: "Ursula Andress starred as Honey Ryder in Dr. No (1962) and later as Vesper Lynd in the 1967 Bond parody Casino Royale. She remains the definitive original Bond girl.", fun_fact: "Her voice in Dr. No was actually dubbed by German actress Nikki van der Zyl because the producers felt her Swiss-German accent was too strong." },
      { round_number: 5, round_label: "THE COMEDY", question_text: "One of them starred alongside Tony Curtis and Jack Lemmon in a 1959 film widely considered the greatest comedy ever made. Which one?", correct_answer: "a", explanation: "Marilyn Monroe starred in Some Like It Hot (1959), directed by Billy Wilder. The American Film Institute named it the funniest American film of all time.", fun_fact: "Director Billy Wilder said working with Monroe was \"like pulling teeth\" but admitted she was \"pure magic on screen.\"" },
      { round_number: 6, round_label: "THE SWISS", question_text: "One of them was born in Ostermundigen, Switzerland, and moved to Rome at 17 to pursue acting \u2014 appearing in Italian films before breaking into Hollywood. Which one?", correct_answer: "b", explanation: "Ursula Andress was born in Switzerland in 1936 and moved to Italy as a teenager. She appeared in several Italian films before being cast in Dr. No, which launched her international career.", fun_fact: "She dated James Dean briefly in the 1950s before his death." },
      { round_number: 7, round_label: "THE MYSTERY", question_text: "One of them died at age 36 under circumstances that remain debated to this day \u2014 officially ruled a \"probable suicide\" from barbiturate overdose. Which one?", correct_answer: "a", explanation: "Marilyn Monroe was found dead on August 4, 1962, at her Los Angeles home. She was 36. The official cause was acute barbiturate poisoning, ruled a probable suicide, though conspiracy theories persist.", fun_fact: "She died just weeks after the \"Happy Birthday, Mr. President\" performance. She was 36. Andress is still alive at 90." }
    ]
  },
  {
    slug: "run-dmc-vs-wu-tang",
    fighter_a_name: "Run-D.M.C.",
    fighter_b_name: "Wu-Tang Clan",
    fighter_a_nickname: "The Kings of Rock",
    fighter_b_nickname: "The 36 Chambers",
    tagline: "Old School vs 36 Chambers",
    matchup_type: "era",
    difficulty: 2,
    rounds: [
      { round_number: 1, round_label: "THE SIZE", question_text: "One of these groups had nine core members \u2014 the largest crew in hip-hop history to function as a single unit. Which one?", correct_answer: "b", explanation: "Wu-Tang Clan had nine original members: RZA, GZA, Ol' Dirty Bastard, Method Man, Raekwon, Ghostface Killah, Inspectah Deck, U-God, and Masta Killa.", fun_fact: "Their contract structure was revolutionary \u2014 members could sign solo deals with any label, while the group stayed together on Loud Records." },
      { round_number: 2, round_label: "THE SHOE", question_text: "One of these groups had a groundbreaking endorsement deal with Adidas \u2014 the first hip-hop sneaker deal in history. Which one?", correct_answer: "a", explanation: "Run-D.M.C. signed a $1.6 million deal with Adidas in 1986 after their song \"My Adidas\" became a hit. It was the first endorsement deal between a hip-hop group and a major athletic brand.", fun_fact: "At a Madison Square Garden concert, they asked fans to hold up their Adidas. An Adidas exec in the audience saw thousands of sneakers in the air and signed the deal the next day." },
      { round_number: 3, round_label: "THE CROSSOVER", question_text: "One of these groups collaborated with Aerosmith on a rock-rap crossover that broke down genre barriers and revived a rock band's career. Which one?", correct_answer: "a", explanation: "Run-D.M.C.'s 1986 collaboration with Aerosmith on \"Walk This Way\" became one of the most important crossover hits in music history. It revived Aerosmith's career and introduced rap to rock audiences.", fun_fact: "The original Aerosmith version was from 1975. Run-D.M.C. had been sampling the beat without knowing who wrote it." },
      { round_number: 4, round_label: "THE ALBUM", question_text: "One of these groups released an album that Martin Shkreli bought the sole copy of for $2 million \u2014 making it the most expensive album ever sold. Which one?", correct_answer: "b", explanation: "Wu-Tang Clan's Once Upon a Time in Shaolin (2015) was produced as a single copy and sold to Martin Shkreli for $2 million. The US government later seized it as part of his fraud case.", fun_fact: "The album was kept in a vault in Morocco. The buyer was contractually forbidden from releasing it commercially for 88 years." },
      { round_number: 5, round_label: "THE FIRST", question_text: "One of these groups was the first hip-hop act inducted into the Rock and Roll Hall of Fame. Which one?", correct_answer: "a", explanation: "Run-D.M.C. was inducted into the Rock and Roll Hall of Fame in 2009, becoming the second hip-hop act ever inducted (after Grandmaster Flash). They were the first hip-hop group.", fun_fact: "Eminem presented their induction, calling them \"the Beatles of hip-hop.\"" },
      { round_number: 6, round_label: "THE PHILOSOPHY", question_text: "One of these groups built their entire aesthetic around kung fu films, chess, and the teachings of the Five Percent Nation. Which one?", correct_answer: "b", explanation: "Wu-Tang Clan's mythology drew heavily from martial arts cinema (particularly Shaw Brothers kung fu films), chess strategy, and Five Percent Nation philosophy. Their debut album is named after the 36th Chamber of Shaolin.", fun_fact: "RZA scored several martial arts films later in his career, including The Man with the Iron Fists (2012)." },
      { round_number: 7, round_label: "THE TRAGEDY", question_text: "One of these groups lost a founding member to a fatal shooting outside a recording studio in 2002. Which one?", correct_answer: "a", explanation: "Jam Master Jay (Jason Mizell) of Run-D.M.C. was shot and killed in his recording studio in Queens, New York, on October 30, 2002. He was 37. The case went unsolved for nearly 20 years before two suspects were convicted in 2024.", fun_fact: "Run-D.M.C. never performed again after his death. The group was permanently retired." }
    ]
  },
  {
    slug: "jordan-vs-erving",
    fighter_a_name: "Michael Jordan",
    fighter_b_name: "Julius Erving",
    fighter_a_nickname: "Air Jordan",
    fighter_b_nickname: "Dr. J",
    tagline: "Air vs Doctor",
    matchup_type: "era",
    difficulty: 2,
    rounds: [
      { round_number: 1, round_label: "THE RINGS", question_text: "One of them won six NBA championships \u2014 going 6-for-6 in Finals appearances, never losing. Which one?", correct_answer: "a", explanation: "Michael Jordan won six titles with the Chicago Bulls (1991, 1992, 1993, 1996, 1997, 1998). He was named Finals MVP all six times. He never lost in the Finals.", fun_fact: "He retired twice during his career \u2014 once to play baseball, once because he ran out of challenges." },
      { round_number: 2, round_label: "THE DUNK", question_text: "One of them won the first-ever Slam Dunk Contest \u2014 held in the ABA, not the NBA \u2014 and popularized dunking from the free-throw line. Which one?", correct_answer: "b", explanation: "Julius Erving won the inaugural ABA Slam Dunk Contest at the 1976 All-Star Game in Denver, famously dunking from the free-throw line. He brought the art of dunking to mainstream basketball.", fun_fact: "Jordan later perfected the free-throw line dunk in the 1988 NBA Dunk Contest \u2014 but Dr. J did it first, 12 years earlier." },
      { round_number: 3, round_label: "THE FLU GAME", question_text: "One of them played through severe food poisoning in Game 5 of the 1997 NBA Finals \u2014 scoring 38 points before collapsing into a teammate's arms. Which one?", correct_answer: "a", explanation: "Michael Jordan's \"Flu Game\" against the Utah Jazz is one of the most legendary performances in sports history. He scored 38 points in 44 minutes, including the go-ahead three-pointer with 25 seconds left.", fun_fact: "It was later revealed to be food poisoning, not flu. His trainer Tim Grover blamed a late-night pizza delivery." },
      { round_number: 4, round_label: "THE LEAGUE", question_text: "One of them is the only player in basketball history to be named MVP in both the ABA and the NBA. Which one?", correct_answer: "b", explanation: "Julius Erving won three ABA MVPs (1974, 1975, 1976) and one NBA MVP (1981). No other player has won the top individual award in both leagues.", fun_fact: "When the ABA merged with the NBA in 1976, Dr. J was the prize acquisition. He made the merger worth it." },
      { round_number: 5, round_label: "THE BRAND", question_text: "One of them has a shoe brand that generates over $5 billion in annual revenue \u2014 more than most NBA teams are worth. Which one?", correct_answer: "a", explanation: "The Air Jordan brand, a subsidiary of Nike, generates over $5 billion annually. Jordan earns approximately $150 million per year from the brand alone \u2014 more than he ever earned playing basketball.", fun_fact: "Nike initially offered him $500,000 per year. His mother told him to take the meeting. The brand is now worth more than many Fortune 500 companies." },
      { round_number: 6, round_label: "THE PIONEER", question_text: "One of them helped legitimize an entire rival basketball league \u2014 making the merger with the NBA possible through his sheer star power. Which one?", correct_answer: "b", explanation: "Dr. J's dominance in the ABA gave the league credibility and forced the NBA to take it seriously. The ABA-NBA merger in 1976 happened largely because teams wanted access to players like Erving.", fun_fact: "He played for the New York Nets in the ABA before being sold to the Philadelphia 76ers for $3 million after the merger." },
      { round_number: 7, round_label: "THE NUMBER", question_text: "One of them wore #23 \u2014 a number that became so iconic it was retired by a team he never even played for. Which one?", correct_answer: "a", explanation: "Michael Jordan's #23 was retired by the Chicago Bulls and the Miami Heat (where he never played). The Heat retired it as a tribute to his impact on the entire sport.", fun_fact: "He briefly wore #45 when he came back from his first retirement in 1995, then switched back to #23 because it felt wrong." }
    ]
  },
  {
    slug: "marley-vs-hendrix",
    fighter_a_name: "Bob Marley",
    fighter_b_name: "Jimi Hendrix",
    fighter_a_nickname: "The Prophet",
    fighter_b_nickname: "The Guitar God",
    tagline: "Roots vs Voltage",
    matchup_type: "crossover",
    difficulty: 3,
    rounds: [
      { round_number: 1, round_label: "THE ANTHEM", question_text: "One of them played a feedback-drenched version of \"The Star-Spangled Banner\" at Woodstock in 1969 that became the defining musical statement of the counterculture era. Which one?", correct_answer: "b", explanation: "Jimi Hendrix's performance of the national anthem at Woodstock on August 18, 1969, used distortion and feedback to evoke the sounds of war. It remains the most famous guitar performance in history.", fun_fact: "He took the stage at 8 AM Monday morning \u2014 rain had delayed the schedule. Only 30,000-40,000 of the original 400,000 attendees were still there." },
      { round_number: 2, round_label: "THE BULLET", question_text: "One of them survived an assassination attempt when seven gunmen raided his home two days before a peace concert. He was shot in the arm but still performed. Which one?", correct_answer: "a", explanation: "Bob Marley was shot at his home at 56 Hope Road in Kingston on December 3, 1976, amid political tensions before Jamaican elections. Despite being wounded, he performed at the Smile Jamaica Concert two days later.", fun_fact: "His wife Rita was also shot \u2014 the bullet grazed her head. Both survived." },
      { round_number: 3, round_label: "THE CLUB", question_text: "One of them died at age 27, becoming a founding member of the infamous \"27 Club\" alongside Janis Joplin, Jim Morrison, and later Kurt Cobain. Which one?", correct_answer: "b", explanation: "Jimi Hendrix died on September 18, 1970, in London at age 27 from asphyxia after ingesting barbiturates. His death, alongside Brian Jones, Janis Joplin, and Jim Morrison, established the tragic \"27 Club\" pattern.", fun_fact: "He had been performing for only four years on the international stage. His entire recorded legacy spans 1966-1970." },
      { round_number: 4, round_label: "THE MOVEMENT", question_text: "One of them became the voice of an entire political and spiritual movement \u2014 with his music inseparable from Rastafari, pan-Africanism, and the struggle for liberation. Which one?", correct_answer: "a", explanation: "Bob Marley's music became the global anthem of Rastafari and the pan-African liberation movement. Songs like \"One Love,\" \"Redemption Song,\" and \"Get Up, Stand Up\" transcended entertainment to become protest hymns.", fun_fact: "His album Exodus (1977) was named the greatest album of the 20th century by Time magazine in 1999." },
      { round_number: 5, round_label: "THE GUITAR", question_text: "One of them was left-handed but played a right-handed Fender Stratocaster flipped upside down \u2014 and could play with his teeth, behind his back, or while setting the guitar on fire. Which one?", correct_answer: "b", explanation: "Hendrix played a right-handed Stratocaster restrung for left-handed playing. His showmanship included playing with his teeth, behind his head, and famously setting his guitar on fire at the Monterey Pop Festival in 1967.", fun_fact: "He was self-taught. He never learned to read music." },
      { round_number: 6, round_label: "THE REGGAE", question_text: "One of them is credited with bringing an entire music genre \u2014 previously confined to a small Caribbean island \u2014 to a worldwide audience. Which one?", correct_answer: "a", explanation: "Bob Marley brought reggae from Jamaica to the world stage. Before him, reggae was virtually unknown outside the Caribbean. His international tours and albums made it a global genre.", fun_fact: "He died on May 11, 1981, at age 36 from melanoma that had spread from under his toenail. He refused amputation on religious grounds." },
      { round_number: 7, round_label: "THE LEGACY", question_text: "Rolling Stone magazine ranked one of them the greatest guitarist of all time. Which one?", correct_answer: "b", explanation: "Jimi Hendrix has been ranked #1 on Rolling Stone's list of the greatest guitarists of all time in every edition of the list. No other guitarist has ever claimed the top spot.", fun_fact: "He achieved this status with a career that lasted barely four years. Most guitarists on the list had decades." }
    ]
  }
];

const combined = [...existing, ...batch4];
writeFileSync("content/deathmatch-matchups.json", JSON.stringify(combined, null, 2));
console.log(`Total matchups: ${combined.length}`);
console.log("Added:", batch4.map(m => m.slug).join(", "));
