import { readFileSync, writeFileSync } from "fs";

const existing = JSON.parse(readFileSync("content/deathmatch-matchups.json", "utf-8"));

const batch5 = [
  {
    slug: "ali-vs-chamberlain",
    fighter_a_name: "Muhammad Ali",
    fighter_b_name: "Wilt Chamberlain",
    fighter_a_nickname: "The Greatest",
    fighter_b_nickname: "The Big Dipper",
    tagline: "The Greatest vs The Giant",
    matchup_type: "crossover",
    difficulty: 2,
    rounds: [
      { round_number: 1, round_label: "THE QUOTE", question_text: "One of them coined \"Float like a butterfly, sting like a bee\" \u2014 perhaps the most famous line in sports history. Which one?", correct_answer: "a", explanation: "Muhammad Ali first used the phrase before his 1964 fight against Sonny Liston. The full quote: \"Float like a butterfly, sting like a bee. The hands can't hit what the eyes can't see.\"", fun_fact: "The line was actually written by his cornerman Drew Bundini Brown, but Ali made it immortal." },
      { round_number: 2, round_label: "THE 100", question_text: "One of them scored 100 points in a single game \u2014 a record that has stood for over 60 years and may never be broken. Which one?", correct_answer: "b", explanation: "Wilt Chamberlain scored 100 points for the Philadelphia Warriors against the New York Knicks on March 2, 1962, in Hershey, Pennsylvania. The final score was 169-147.", fun_fact: "No video of the full game exists. Only an audio recording and the famous photo of Wilt holding a paper reading \"100\" survive." },
      { round_number: 3, round_label: "THE STAND", question_text: "One of them refused to be drafted into the Vietnam War, was stripped of his heavyweight title, and banned from boxing for three years. Which one?", correct_answer: "a", explanation: "Ali refused induction into the US Army in 1967, saying \"I ain't got no quarrel with them Viet Cong.\" He was stripped of his title, convicted of draft evasion, and didn't fight for over three years during his prime.", fun_fact: "The Supreme Court unanimously overturned his conviction in 1971. He came back and won the title twice more." },
      { round_number: 4, round_label: "THE CLAIM", question_text: "One of them claimed in his autobiography to have slept with 20,000 women \u2014 a number he later said was just \"a nice round figure.\" Which one?", correct_answer: "b", explanation: "Wilt Chamberlain made the claim in his 1991 autobiography A View From Above. He later clarified he was looking for a number that conveyed how big a role women played in his life as a bachelor athlete.", fun_fact: "His teammate Jerry West said: \"Wilt had a tendency to elaborate things and make him bigger than life.\"" },
      { round_number: 5, round_label: "THE ALMOST FIGHT", question_text: "These two almost fought each other in a boxing match at the Houston Astrodome in 1971. Contracts were drawn up but one of them backed out. Who was supposed to be the challenger?", correct_answer: "b", explanation: "Wilt Chamberlain agreed to a non-title boxing match against Ali. A press conference was planned, but Chamberlain's lawyers and his father convinced him to drop out. Ali taunted: \"Timber! The tree will fall.\"", fun_fact: "Chamberlain was 7'1\" and 275 pounds. Ali was 6'3\" and 215 pounds. It would have been the most insane sporting event of the decade." },
      { round_number: 6, round_label: "THE NAME", question_text: "One of them changed his name from Cassius Marcellus Clay Jr. after joining the Nation of Islam, and refused to answer to his old name. Which one?", correct_answer: "a", explanation: "Ali converted to Islam and changed his name in 1964. He famously told Ernie Terrell in the ring: \"What's my name?!\" while punishing him for using \"Clay.\"", fun_fact: "His father, Cassius Sr., was named after the 19th-century Kentucky abolitionist Cassius Marcellus Clay." },
      { round_number: 7, round_label: "THE RECORD", question_text: "One of them averaged 50.4 points per game for an entire NBA season \u2014 a record so absurd it sounds made up. Which one?", correct_answer: "b", explanation: "Wilt Chamberlain averaged 50.4 points per game during the 1961-62 season. He also averaged 48.5 minutes per game that season \u2014 in a sport with 48-minute games \u2014 because of overtime.", fun_fact: "He never fouled out of a single game in his entire 14-year career. Not once." }
    ]
  },
  {
    slug: "best-vs-gascoigne",
    fighter_a_name: "George Best",
    fighter_b_name: "Paul Gascoigne",
    fighter_a_nickname: "The Belfast Boy",
    fighter_b_nickname: "Gazza",
    tagline: "Belfast Boy vs Gazza",
    matchup_type: "rivalry",
    difficulty: 2,
    rounds: [
      { round_number: 1, round_label: "THE QUOTE", question_text: "One of them said: \"I spent a lot of money on booze, birds, and fast cars. The rest I just squandered.\" Which one?", correct_answer: "a", explanation: "George Best delivered this line, which became one of the most quoted sentences in football history. It perfectly captured his legendary talent and equally legendary self-destruction.", fun_fact: "He also said: \"In 1969 I gave up women and alcohol \u2014 it was the worst 20 minutes of my life.\"" },
      { round_number: 2, round_label: "THE TEARS", question_text: "One of them cried on camera during a World Cup semi-final after receiving a yellow card that would have ruled him out of the final. The image became one of football's most iconic moments. Which one?", correct_answer: "b", explanation: "Paul Gascoigne's tears during England's 1990 World Cup semi-final against West Germany in Turin became the defining image of Italia '90. The booking meant he'd miss the final if England won.", fun_fact: "England lost on penalties. The tears were for nothing \u2014 except making him the most loved footballer in England." },
      { round_number: 3, round_label: "THE CLUB", question_text: "One of them played for Manchester United from age 17 and scored 179 goals in 470 appearances \u2014 becoming the greatest talent Old Trafford had ever seen. Which one?", correct_answer: "a", explanation: "George Best joined Manchester United as a 15-year-old in 1961 and made his debut at 17. He won two league titles and the European Cup in 1968, the same year he won the Ballon d'Or.", fun_fact: "Matt Busby's scout sent him a telegram after watching Best trial: \"I think I've found you a genius.\"" },
      { round_number: 4, round_label: "THE DENTIST'S CHAIR", question_text: "One of them was photographed having alcohol poured down his throat in a dentist's chair during a team trip to Hong Kong before Euro 96. Which one?", correct_answer: "b", explanation: "Gascoigne was at the center of the infamous \"Dentist's Chair\" incident in Hong Kong in 1996. After photos leaked of players in a nightclub bar, he celebrated a goal at Euro 96 by lying on the pitch while teammates squirted water into his mouth.", fun_fact: "The goal celebration re-enactment against Scotland at Wembley is one of the greatest moments in England football history." },
      { round_number: 5, round_label: "THE AWARD", question_text: "One of them won the Ballon d'Or \u2014 European Footballer of the Year \u2014 at age 22. Which one?", correct_answer: "a", explanation: "George Best won the 1968 Ballon d'Or after leading Manchester United to the European Cup. He scored in the final against Benfica at Wembley.", fun_fact: "Pel\u00e9 said Best was \"the greatest player in the world\" \u2014 the highest compliment from the king himself." },
      { round_number: 6, round_label: "THE GOAL", question_text: "One of them scored a solo goal against Scotland where he flicked the ball over Colin Hendry's head, ran around him, and volleyed it in \u2014 a goal so audacious it defined an entire tournament. Which one?", correct_answer: "b", explanation: "Gascoigne's goal against Scotland at Euro 96 is considered one of the greatest ever scored at a European Championship. He flicked the ball over Hendry's head with his left foot and volleyed with his right.", fun_fact: "He then slid across the Wembley turf for the Dentist's Chair celebration. The whole country lost its mind." },
      { round_number: 7, round_label: "THE END", question_text: "One of them died at 59 from organ failure related to decades of alcoholism, after receiving a liver transplant three years earlier. Which one?", correct_answer: "a", explanation: "George Best died on November 25, 2005, at age 59. His body failed after years of alcohol abuse, despite a liver transplant in 2002. He once said from his hospital bed: \"Don't die like me.\"", fun_fact: "Gascoigne, now in his late 50s, continues to battle addiction publicly. Both men's stories are warnings wrapped in genius." }
    ]
  },
  {
    slug: "ronaldo-vs-higuita",
    fighter_a_name: "Ronaldo",
    fighter_b_name: "Ren\u00e9 Higuita",
    fighter_a_nickname: "The Phenomenon",
    fighter_b_nickname: "El Loco",
    tagline: "The Phenomenon vs The Scorpion",
    matchup_type: "crossover",
    difficulty: 3,
    rounds: [
      { round_number: 1, round_label: "THE KICK", question_text: "One of them invented a save so outrageous it got its own name \u2014 diving forward and kicking the ball away with both heels behind his back at Wembley in 1995. Which one?", correct_answer: "b", explanation: "Ren\u00e9 Higuita performed the \"Scorpion Kick\" save against England at Wembley on September 6, 1995, clearing a Jamie Redknapp cross. It became one of the most replayed moments in football history.", fun_fact: "He got the idea after watching a child do a similar kick during a TV commercial shoot." },
      { round_number: 2, round_label: "THE MYSTERY", question_text: "One of them suffered a seizure hours before a World Cup final, was initially dropped from the team sheet, then mysteriously reinstated and played poorly as his team lost 3-0. Which one?", correct_answer: "a", explanation: "Ronaldo had convulsions in his hotel room before the 1998 World Cup final against France. He was unconscious for 30-40 seconds. He insisted on playing despite being visibly unwell. Brazil lost 3-0.", fun_fact: "Conspiracy theories persist. Some blamed Nike's sponsorship pressure. Ronaldo himself has never fully explained what happened." },
      { round_number: 3, round_label: "THE CONNECTION", question_text: "One of them was jailed for seven months for acting as a go-between in a kidnapping linked to Pablo Escobar. Which one?", correct_answer: "b", explanation: "Higuita was imprisoned in 1993 for delivering ransom money that secured the release of a drug cartel associate's daughter. He went on a two-week hunger strike in prison before being released without charge.", fun_fact: "He has never hidden his friendship with Escobar and visited him in prison." },
      { round_number: 4, round_label: "THE COMEBACK", question_text: "One of them won the World Cup in 2002 despite being told his career was over after multiple devastating knee injuries. He scored both goals in the final. Which one?", correct_answer: "a", explanation: "Ronaldo suffered two career-threatening knee injuries (1999 and 2000) but came back to win the 2002 World Cup, scoring 8 goals in the tournament including both in the 2-0 final against Germany.", fun_fact: "His iconic shaved-head-with-a-front-triangle hairstyle from that tournament was deliberately ugly. He said he did it so reporters would ask about his hair instead of his knee." },
      { round_number: 5, round_label: "THE POSITION", question_text: "One of them was a goalkeeper who regularly dribbled the ball past the halfway line, took free kicks, and played like an outfield player \u2014 earning the nickname \"El Loco.\" Which one?", correct_answer: "b", explanation: "Higuita was famous for abandoning his goal to dribble upfield. His style revolutionized the goalkeeper position but also led to disasters \u2014 most famously when Roger Milla tackled him in the 1990 World Cup, ending Colombia's run.", fun_fact: "He is considered a spiritual predecessor to Manuel Neuer's \"sweeper-keeper\" style." },
      { round_number: 6, round_label: "THE GOALS", question_text: "One of them scored 352 goals in 518 career matches, including 62 in 98 appearances for his national team, and was named FIFA World Player of the Year three times. Which one?", correct_answer: "a", explanation: "Ronaldo won FIFA World Player of the Year in 1996, 1997, and 2002. He scored for Barcelona, Inter Milan, Real Madrid, and AC Milan across a legendary career.", fun_fact: "Zinedine Zidane called him \"the greatest player I ever played with or against.\"" },
      { round_number: 7, round_label: "THE HAIR", question_text: "One of them was as famous for his wild, curly hair as for his goalkeeping \u2014 the hair became inseparable from the legend. Which one?", correct_answer: "b", explanation: "Higuita's massive mane of curly hair became his visual trademark, as recognizable as his scorpion kick. It made him look even more unhinged as he charged upfield with the ball.", fun_fact: "Ronaldo's 2002 triangle haircut was deliberately ridiculous. Higuita's hair was just... Higuita." }
    ]
  },
  {
    slug: "ashe-vs-noah",
    fighter_a_name: "Arthur Ashe",
    fighter_b_name: "Yannick Noah",
    fighter_a_nickname: "The Pioneer",
    fighter_b_nickname: "The Showman",
    tagline: "Barrier Breakers",
    matchup_type: "rivalry",
    difficulty: 3,
    rounds: [
      { round_number: 1, round_label: "THE BARRIER", question_text: "One of them became the first Black man to win the US Open (1968) and Wimbledon (1975) \u2014 breaking through racial barriers in a sport that had excluded Black players for decades. Which one?", correct_answer: "a", explanation: "Arthur Ashe won the US Open in 1968 and Wimbledon in 1975. He remains the only Black man to have won singles titles at Wimbledon, the US Open, and the Australian Open.", fun_fact: "He grew up in segregated Richmond, Virginia, where he was not allowed to play on public tennis courts." },
      { round_number: 2, round_label: "THE LAST", question_text: "One of them is the last man from his country to win his home Grand Slam \u2014 a drought that has lasted over 40 years and counting. Which one?", correct_answer: "b", explanation: "Yannick Noah won the French Open in 1983. No Frenchman has won Roland Garros since. The drought is one of the longest in tennis.", fun_fact: "He beat Mats Wilander in the final. The entire stadium erupted. It remains one of the most emotional moments in French sports history." },
      { round_number: 3, round_label: "THE DISCOVERY", question_text: "One of them was discovered as a child playing tennis in Cameroon by a visiting American tennis legend \u2014 who sponsored his move to Europe to train. Which one?", correct_answer: "b", explanation: "Yannick Noah was spotted by Arthur Ashe himself during a tennis clinic in Yaound\u00e9, Cameroon, in 1971. Ashe helped arrange for the 11-year-old Noah to train at the French Tennis Federation.", fun_fact: "The man who discovered him was the other fighter in this matchup. Their stories are forever linked." },
      { round_number: 4, round_label: "THE SECOND CAREER", question_text: "One of them became a successful pop singer after retiring from tennis, releasing multiple albums and performing across Europe. Which one?", correct_answer: "b", explanation: "Yannick Noah launched a music career in 1991 with the album Black & What. His single \"Saga Africa\" became a massive hit in France. He has released multiple albums and performs to large audiences.", fun_fact: "He returned to Roland Garros 40 years after his 1983 title \u2014 this time with a microphone, not a racket." },
      { round_number: 5, round_label: "THE ACTIVISM", question_text: "One of them was arrested protesting apartheid outside the South African embassy in Washington, D.C. \u2014 fighting for the same cause that had banned him from playing in the South African Open. Which one?", correct_answer: "a", explanation: "Arthur Ashe was a vocal critic of apartheid and was arrested in 1985 during an anti-apartheid protest outside the South African embassy. South Africa had denied him a visa to play in 1969.", fun_fact: "He co-founded Artists and Athletes Against Apartheid and campaigned until the system fell." },
      { round_number: 6, round_label: "THE GIANT UPSET", question_text: "One of them defeated the defending champion and overwhelming favorite Jimmy Connors in the Wimbledon final \u2014 using a tactical masterclass of slow, soft shots to neutralize Connors's power. Which one?", correct_answer: "a", explanation: "Arthur Ashe defeated Jimmy Connors in the 1975 Wimbledon final using a strategy of junk balls, slices, and changes of pace. Nobody expected it to work. It was chess against a sledgehammer.", fun_fact: "Ashe was 31. Most people thought he was past his prime. He proved them all wrong." },
      { round_number: 7, round_label: "THE FAREWELL", question_text: "One of them contracted HIV from a blood transfusion during heart surgery \u2014 and spent his final years educating the public about AIDS before dying at 49. Which one?", correct_answer: "a", explanation: "Arthur Ashe contracted HIV from a blood transfusion during heart bypass surgery in 1983. He went public in 1992 and spent his remaining time as an AIDS awareness advocate. He died on February 6, 1993.", fun_fact: "The main stadium at the US Open is named Arthur Ashe Stadium. It is the largest tennis arena in the world." }
    ]
  },
  {
    slug: "beamon-vs-fosbury",
    fighter_a_name: "Bob Beamon",
    fighter_b_name: "Dick Fosbury",
    fighter_a_nickname: "The Leap",
    fighter_b_nickname: "The Flop",
    tagline: "The Leap vs The Flop",
    matchup_type: "rivalry",
    difficulty: 3,
    rounds: [
      { round_number: 1, round_label: "THE RECORD", question_text: "One of them broke the world record by nearly two feet in a single jump \u2014 a margin so absurd that he collapsed in shock and had to be helped off the field. Which one?", correct_answer: "a", explanation: "Bob Beamon leapt 8.90 meters (29 feet 2\u00bc inches) at the 1968 Mexico City Olympics, breaking the existing record by 55 cm. Officials had to use a tape measure because the optical device didn't reach far enough.", fun_fact: "When told the distance, Beamon collapsed. His teammate Ralph Boston said: \"You have destroyed this event.\"" },
      { round_number: 2, round_label: "THE REVOLUTION", question_text: "One of them invented a technique so revolutionary that within 4 years, the majority of competitors had adopted it \u2014 and today virtually every athlete in the sport uses it. Which one?", correct_answer: "b", explanation: "Dick Fosbury introduced the \"Fosbury Flop\" \u2014 going over the bar back-first instead of face-down. At the 1972 Olympics, 28 of 40 high jumpers used his technique. Today, every competitive high jumper does.", fun_fact: "Before Fosbury, jumpers went over face-down (straddle technique). His coach initially tried to talk him out of the back-first approach." },
      { round_number: 3, round_label: "THE CITY", question_text: "Both competed at the same Olympics. One won gold in the long jump, the other in the high jump. Which city hosted those Games?", correct_answer: "a", explanation: "Both Bob Beamon and Dick Fosbury won gold medals at the 1968 Summer Olympics in Mexico City. The thin air at altitude (2,240 meters) contributed to Beamon's extraordinary distance.", fun_fact: "The 1968 Mexico City Olympics were also where Tommie Smith and John Carlos raised their fists on the podium." },
      { round_number: 4, round_label: "THE DURATION", question_text: "One of them set a world record that stood for 23 years \u2014 from 1968 until 1991. Which one?", correct_answer: "a", explanation: "Bob Beamon's long jump record of 8.90m stood from October 18, 1968, until August 30, 1991, when Mike Powell jumped 8.95m in Tokyo. It remains the Olympic record to this day.", fun_fact: "For context, the previous record had been broken 13 times in the 8 years before Beamon. His record lasted nearly a quarter century." },
      { round_number: 5, round_label: "THE HEIGHT", question_text: "One of them set a new Olympic record of 2.24 meters (7 feet 4\u00bc inches) using a technique that spectators initially laughed at because it looked so strange. Which one?", correct_answer: "b", explanation: "Dick Fosbury won gold at 2.24m with his back-first technique. Crowds and commentators were baffled by his approach, but the results were undeniable.", fun_fact: "His high school coach had begged him to use the conventional straddle technique. Fosbury ignored him and changed the sport forever." },
      { round_number: 6, round_label: "THE NAME", question_text: "One of them had his technique named after him \u2014 a term that is now in the dictionary and used in business and innovation metaphors worldwide. Which one?", correct_answer: "b", explanation: "The \"Fosbury Flop\" is one of the most famous named techniques in all of sports. The term has entered common language as a metaphor for unconventional thinking that revolutionizes an entire field.", fun_fact: "A newspaper reporter in Fosbury's hometown of Medford, Oregon, coined the term. Fosbury himself just called it \"going over backwards.\"" },
      { round_number: 7, round_label: "THE ONE-HIT", question_text: "One of them never came close to repeating his Olympic performance \u2014 his greatest moment was so far beyond anything else he ever did that it seemed like a miracle. Which one?", correct_answer: "a", explanation: "Bob Beamon never jumped beyond 27 feet again after his 29-foot-2 leap in Mexico City. He retired from athletics in 1976 without ever approaching the record. It truly was a once-in-a-lifetime moment.", fun_fact: "Scientists later calculated that everything aligned: altitude, wind, takeoff angle, and speed. It was a perfect storm of physics and human ability." }
    ]
  }
];

const combined = [...existing, ...batch5];
writeFileSync("content/deathmatch-matchups.json", JSON.stringify(combined, null, 2));
console.log(`Total matchups: ${combined.length}`);
console.log("Added:", batch5.map(m => m.slug).join(", "));
