import { readFileSync, writeFileSync } from "fs";

const existing = JSON.parse(readFileSync("content/deathmatch-matchups.json", "utf-8"));

const batch8 = [
  {
    slug: "beastie-boys-vs-tribe",
    fighter_a_name: "Beastie Boys",
    fighter_b_name: "A Tribe Called Quest",
    fighter_a_nickname: "The Brats",
    fighter_b_nickname: "The Abstract",
    tagline: "White Noise vs Jazz Rap",
    matchup_type: "music",
    difficulty: 2,
    rounds: [
      { round_number: 1, round_label: "THE FIRST", question_text: "One of these groups released the first rap album ever to reach #1 on the Billboard 200 \u2014 a punk-rap debut that sold 10 million copies. Which one?", correct_answer: "a", explanation: "Beastie Boys' Licensed to Ill topped the Billboard 200 on March 7, 1987, becoming the first hip-hop album to reach #1. It was certified Diamond by the RIAA.", fun_fact: "They started as a hardcore punk band before switching to rap after meeting Rick Rubin." },
      { round_number: 2, round_label: "THE JAZZ", question_text: "One of these groups fused jazz samples with hip-hop on their second album \u2014 creating a subgenre and releasing what many consider the greatest hip-hop album ever made. Which one?", correct_answer: "b", explanation: "A Tribe Called Quest's The Low End Theory (1991) pioneered jazz rap with its minimalist production, upright bass samples, and cerebral lyricism. It is consistently ranked among the greatest albums of all time.", fun_fact: "Q-Tip produced nearly the entire album himself, sampling jazz legends like Art Blakey and Ron Carter." },
      { round_number: 3, round_label: "THE PARTY", question_text: "One of these groups wrote \"(You Gotta) Fight for Your Right (to Party!)\" as a satire of party culture \u2014 but it was taken at face value and became a genuine frat-boy anthem. Which one?", correct_answer: "a", explanation: "Beastie Boys wrote the song as a parody of mindless party tracks. It reached #7 on the Hot 100 and became their only top-10 hit. They later expressed regret that the satire was lost.", fun_fact: "Ad-Rock later said: \"The fact that people didn't understand it was a joke was disappointing.\"" },
      { round_number: 4, round_label: "THE LOSS", question_text: "One of these groups lost a founding member to diabetes complications at age 45 \u2014 then released one final album as a tribute. Which one?", correct_answer: "b", explanation: "Phife Dawg (Malik Taylor) of A Tribe Called Quest died on March 22, 2016, from complications of diabetes. The group released We Got It from Here... Thank You 4 Your Service later that year as their farewell.", fun_fact: "He had been battling diabetes since his 20s and received a kidney transplant in 2008." },
      { round_number: 5, round_label: "THE EVOLUTION", question_text: "One of these groups completely reinvented their sound across three decades \u2014 going from punk-rap to jazz-funk sampling to psychedelic instrumentals \u2014 releasing Paul's Boutique, Check Your Head, and Ill Communication. Which one?", correct_answer: "a", explanation: "Beastie Boys' musical evolution is unmatched in hip-hop. Paul's Boutique (1989) was a commercial flop but a critical masterpiece. By Hello Nasty (1998) they were blending electronic, punk, and funk.", fun_fact: "Paul's Boutique sampled over 300 different recordings. It could never be made today due to sample clearance costs." },
      { round_number: 6, round_label: "THE COLLECTIVE", question_text: "One of these groups was part of a larger collective called the Native Tongues \u2014 alongside De La Soul, Jungle Brothers, and Queen Latifah \u2014 representing conscious, Afrocentric hip-hop. Which one?", correct_answer: "b", explanation: "A Tribe Called Quest was a core member of the Native Tongues collective, which promoted positivity, Afrocentrism, and musical experimentation in hip-hop as a counterpoint to gangsta rap.", fun_fact: "The Native Tongues were hip-hop's art school movement. While N.W.A. was burning the house down, they were painting it." },
      { round_number: 7, round_label: "THE HALL", question_text: "One of these groups was inducted into the Rock and Roll Hall of Fame in 2012. Which one?", correct_answer: "a", explanation: "Beastie Boys were inducted into the Rock and Roll Hall of Fame in 2012. MCA (Adam Yauch) had died of cancer just weeks before the ceremony. Ad-Rock and Mike D accepted without him.", fun_fact: "Yauch's will stipulated that Beastie Boys' music can never be used in advertising. The group is permanently retired." }
    ]
  },
  {
    slug: "queen-vs-acdc",
    fighter_a_name: "Queen",
    fighter_b_name: "Angus Young",
    fighter_a_nickname: "The Champions",
    fighter_b_nickname: "Highway to Hell",
    tagline: "Bohemian vs Highway to Hell",
    matchup_type: "music",
    difficulty: 2,
    rounds: [
      { round_number: 1, round_label: "THE STREAM", question_text: "One of these bands recorded the most-streamed song from the 20th century \u2014 surpassing 1.6 billion streams globally. Which one?", correct_answer: "a", explanation: "Queen's \"Bohemian Rhapsody\" became the most-streamed song of the 20th century in 2018, surpassing Nirvana's \"Smells Like Teen Spirit\" and Guns N' Roses' \"Sweet Child o' Mine.\"", fun_fact: "The song is 5 minutes 55 seconds long. Radio stations initially refused to play it because it was too long. It hit #1 anyway." },
      { round_number: 2, round_label: "THE ALBUM", question_text: "One of these bands released Back in Black \u2014 the second best-selling album in music history with over 50 million copies sold. Which one?", correct_answer: "b", explanation: "AC/DC's Back in Black (1980) has sold over 50 million copies, behind only Michael Jackson's Thriller. It was recorded as a tribute to their original singer who had died months earlier.", fun_fact: "Only Thriller has sold more. Back in Black outsold every Beatles album, every Elvis album, and every other rock album ever made." },
      { round_number: 3, round_label: "THE DEATH", question_text: "One of these bands lost their original lead singer to acute alcohol poisoning at age 33 \u2014 then replaced him and immediately recorded their greatest album. Which one?", correct_answer: "b", explanation: "AC/DC's Bon Scott died on February 19, 1980, after a night of heavy drinking in London. He was 33. The band recruited Brian Johnson and recorded Back in Black five months later.", fun_fact: "The album's all-black cover was a tribute to Scott. No text, no images \u2014 just black." },
      { round_number: 4, round_label: "THE LIVE AID", question_text: "One of these bands delivered what was voted the greatest live performance in rock history \u2014 a 21-minute set at Wembley Stadium in 1985. Which one?", correct_answer: "a", explanation: "Queen's Live Aid performance on July 13, 1985, was voted the greatest live rock performance ever in a 2005 poll. Freddie Mercury's call-and-response with 72,000 people became \"The Note Heard Round the World.\"", fun_fact: "They hadn't rehearsed for months. Mercury just walked out and owned 72,000 people in seconds." },
      { round_number: 5, round_label: "THE UNIFORM", question_text: "One of these bands has a guitarist famous for performing in a schoolboy uniform \u2014 complete with shorts, blazer, tie, and a satchel \u2014 at every single show for over 50 years. Which one?", correct_answer: "b", explanation: "Angus Young has worn his schoolboy uniform at every AC/DC concert since the mid-1970s. His sister originally suggested the outfit. He also does a signature move called the \"duckwalk\" across the stage.", fun_fact: "He tried other costumes early on \u2014 including Spider-Man and a gorilla suit \u2014 but the schoolboy stuck." },
      { round_number: 6, round_label: "THE OPERA", question_text: "One of these bands recorded a song that shifts between ballad, opera, and hard rock \u2014 with no chorus \u2014 and it became a #1 hit twice, 16 years apart. Which one?", correct_answer: "a", explanation: "Queen's \"Bohemian Rhapsody\" hit #1 in 1975 and again in 1991 after Freddie Mercury's death and its appearance in Wayne's World. No other song has reached #1 in two different decades.", fun_fact: "The operatic section required 180 overdubs. The tape was worn nearly transparent from re-recording." },
      { round_number: 7, round_label: "THE SALES", question_text: "One of these bands has sold an estimated 300 million records worldwide. The other has sold 200 million. Who sold 300 million?", correct_answer: "a", explanation: "Queen has sold an estimated 300 million records worldwide. AC/DC has sold approximately 200 million. Both are among the top 10 best-selling music acts of all time.", fun_fact: "Combined, these two bands have sold half a billion records. And people say rock is dead." }
    ]
  },
  {
    slug: "summer-vs-harry",
    fighter_a_name: "Donna Summer",
    fighter_b_name: "Debbie Harry",
    fighter_a_nickname: "The Queen of Disco",
    fighter_b_nickname: "The Queen of Punk",
    tagline: "Disco Queen vs Punk Queen",
    matchup_type: "music",
    difficulty: 2,
    rounds: [
      { round_number: 1, round_label: "THE REVOLUTION", question_text: "One of them recorded \"I Feel Love\" (1977) \u2014 a track built entirely on synthesizers that invented electronic dance music and changed pop production forever. Which one?", correct_answer: "a", explanation: "Donna Summer and producer Giorgio Moroder created \"I Feel Love\" using a Moog synthesizer. Brian Eno reportedly played it for David Bowie and said: \"This is the sound of the future.\"", fun_fact: "The track dispensed with live instruments entirely. Every sound except Summer's voice was electronic. In 1977, that was unthinkable." },
      { round_number: 2, round_label: "THE RAP", question_text: "One of them had the first #1 single in US history to feature rap vocals \u2014 in 1981, years before rap went mainstream. Which one?", correct_answer: "b", explanation: "Debbie Harry and Blondie's \"Rapture\" hit #1 on the Billboard Hot 100 in March 1981. It was also the first rap video aired on MTV. Harry rapped the verses herself.", fun_fact: "She name-checks Fab Five Freddy and Grandmaster Flash in the lyrics \u2014 bridging downtown punk and uptown hip-hop." },
      { round_number: 3, round_label: "THE 17 MINUTES", question_text: "One of them recorded \"Love to Love You Baby\" \u2014 a 17-minute track featuring simulated orgasms that was banned by the BBC and became a disco anthem. Which one?", correct_answer: "a", explanation: "Donna Summer recorded the extended version of \"Love to Love You Baby\" at Giorgio Moroder's request. It featured an estimated 22 simulated orgasms. The BBC banned it. It hit #2 in the US.", fun_fact: "She recorded the vocals lying on the studio floor with the lights dimmed. Moroder kept the tape rolling." },
      { round_number: 4, round_label: "THE CLUB", question_text: "One of them was a regular at CBGB alongside the Ramones and Talking Heads \u2014 the epicenter of New York punk. Which one?", correct_answer: "b", explanation: "Debbie Harry and Blondie were a CBGB house band from 1974. The club on the Bowery incubated the punk and new wave movement. Harry made it glamorous.", fun_fact: "CBGB stood for \"Country, Bluegrass, and Blues\" \u2014 which is almost nothing like what was actually played there." },
      { round_number: 5, round_label: "THE FIVE GRAMMYS", question_text: "One of them won five Grammy Awards across her career and was the first artist to have three consecutive double albums reach #1 on the Billboard 200. Which one?", correct_answer: "a", explanation: "Donna Summer won five Grammys and made chart history with three consecutive double albums at #1: Live and More, Bad Girls, and On the Radio. No artist had done that before.", fun_fact: "She was so dominant in the late 1970s that she was called the \"Queen of Disco\" \u2014 a title no one has ever challenged." },
      { round_number: 6, round_label: "THE CROSSING", question_text: "One of them crossed from punk to disco to rap on a single album \u2014 bridging genres that were supposedly at war with each other. Which one?", correct_answer: "b", explanation: "Blondie's Parallel Lines (1978) and Eat to the Beat (1979) fused punk energy with disco hooks. Then \"Rapture\" (1981) added rap. Harry proved genres were boundaries only for people without imagination.", fun_fact: "Punk purists hated \"Heart of Glass\" for being too disco. Harry didn't care. It sold millions." },
      { round_number: 7, round_label: "THE TITLE", question_text: "One of them holds the title \"Queen of Disco\" \u2014 the definitive voice of the biggest musical movement of the 1970s. Which one?", correct_answer: "a", explanation: "Donna Summer is universally known as the Queen of Disco. Her hits \u2014 \"Hot Stuff,\" \"Bad Girls,\" \"Last Dance,\" \"On the Radio\" \u2014 defined the era. She sold over 100 million records worldwide.", fun_fact: "She died on May 17, 2012, at age 63, from lung cancer. She was a non-smoker \u2014 she believed the cancer came from inhaling toxic particles during 9/11." }
    ]
  },
  {
    slug: "grier-vs-bardot",
    fighter_a_name: "Pam Grier",
    fighter_b_name: "Brigitte Bardot",
    fighter_a_nickname: "Foxy Brown",
    fighter_b_nickname: "BB",
    tagline: "The Baddest vs The Bombshell",
    matchup_type: "film",
    difficulty: 2,
    rounds: [
      { round_number: 1, round_label: "THE FIRST", question_text: "One of them is considered the first African American woman to headline an action film \u2014 kicking down doors years before Sigourney Weaver or Linda Hamilton. Which one?", correct_answer: "a", explanation: "Pam Grier headlined Coffy (1973) and Foxy Brown (1974), becoming the first Black woman to carry an action movie. She did it a decade before mainstream Hollywood caught up.", fun_fact: "Quentin Tarantino called her \"the first female action star\" \u2014 and wrote Jackie Brown (1997) specifically for her." },
      { round_number: 2, round_label: "THE SYMBOL", question_text: "One of them became such a powerful symbol of sexual liberation in 1950s France that her initials alone \u2014 two letters \u2014 were enough to identify her worldwide. Which one?", correct_answer: "b", explanation: "Brigitte Bardot \u2014 known simply as \"BB\" \u2014 became the global symbol of French sexuality after And God Created Woman (1956). The film scandalized audiences and made her the most famous woman in Europe.", fun_fact: "She was so famous that the French town of Saint-Tropez became a tourist destination solely because she lived there." },
      { round_number: 3, round_label: "THE REVENGE", question_text: "One of them starred in Coffy (1973) \u2014 playing a nurse who goes on a violent vigilante rampage against drug dealers who got her little sister hooked on heroin. Which one?", correct_answer: "a", explanation: "Pam Grier starred as Coffy, a one-woman army against the drug trade. The film was a huge box office hit and established the blaxploitation action heroine template.", fun_fact: "She did many of her own stunts. The fight scenes were raw and brutal by 1970s standards." },
      { round_number: 4, round_label: "THE ANIMALS", question_text: "One of them quit acting entirely to dedicate her life to animal rights \u2014 founding a foundation that has fought against seal hunting, bullfighting, and fur trapping for over 40 years. Which one?", correct_answer: "b", explanation: "Brigitte Bardot retired from acting in 1973 at age 39 and founded the Brigitte Bardot Foundation in 1986. She has spent more years fighting for animals than she ever spent in cinema.", fun_fact: "She auctioned off her jewelry and personal belongings to fund the foundation. She chose animals over glamour." },
      { round_number: 5, round_label: "THE TARANTINO", question_text: "One of them had their career revived by Quentin Tarantino, who wrote a starring role specifically for her in a 1997 crime film. Which one?", correct_answer: "a", explanation: "Tarantino wrote Jackie Brown (1997) as a love letter to Pam Grier and 1970s blaxploitation cinema. The role earned her a Screen Actors Guild nomination and proved she could carry a film 25 years later.", fun_fact: "Tarantino said he grew up watching her films and always wanted to make a movie with her. Jackie Brown was his chance." },
      { round_number: 6, round_label: "THE KITTEN", question_text: "One of them was so iconic in the 1950s that the French government used her face as the model for Marianne \u2014 the national symbol of the French Republic. Which one?", correct_answer: "b", explanation: "Brigitte Bardot served as the model for Marianne, the bust that appears in every French town hall and is the national personification of France. She was chosen for her beauty and cultural significance.", fun_fact: "Other women who later served as Marianne include Catherine Deneuve and Laetitia Casta." },
      { round_number: 7, round_label: "THE GENRE", question_text: "One of them defined an entire film genre \u2014 blaxploitation \u2014 that put Black heroes at the center of action cinema for the first time. Which one?", correct_answer: "a", explanation: "Pam Grier is the defining star of blaxploitation cinema. Her films \u2014 Coffy, Foxy Brown, Sheba Baby, Friday Foster \u2014 created the template for the Black female action hero.", fun_fact: "The genre was criticized for stereotypes but celebrated for putting Black faces on movie posters and in leading roles for the first time." }
    ]
  },
  {
    slug: "campbell-vs-nielsen",
    fighter_a_name: "Naomi Campbell",
    fighter_b_name: "Brigitte Nielsen",
    fighter_a_nickname: "The Supermodel",
    fighter_b_nickname: "The Amazon",
    tagline: "The Supermodel vs The Amazon",
    matchup_type: "crossover",
    difficulty: 2,
    rounds: [
      { round_number: 1, round_label: "THE COVER", question_text: "One of them was the first Black woman on the cover of French Vogue \u2014 and she was only 18 years old. Which one?", correct_answer: "a", explanation: "Naomi Campbell appeared on the cover of French Vogue in 1988 at age 18, breaking a major barrier in fashion. She went on to become one of the original \"Big Six\" supermodels of the 1990s.", fun_fact: "She was discovered at 15 while shopping in Covent Garden, London." },
      { round_number: 2, round_label: "THE ROCKY", question_text: "One of them married Sylvester Stallone after meeting him on the set of Rocky IV \u2014 a marriage that lasted less than two years. Which one?", correct_answer: "b", explanation: "Brigitte Nielsen married Stallone on December 15, 1985, after appearing in Rocky IV as Ludmilla, Ivan Drago's wife. They divorced in July 1987. She later said Hollywood blacklisted her after the split.", fun_fact: "She was 6'1\" and towered over most of her co-stars. In heels, she was taller than Stallone." },
      { round_number: 3, round_label: "THE PHONE", question_text: "One of them became notorious for throwing a cell phone at her maid \u2014 an assault charge that followed her for years and spawned endless tabloid coverage. Which one?", correct_answer: "a", explanation: "Naomi Campbell pleaded guilty to misdemeanor assault in 2007 for throwing her phone at a maid during a dispute over missing jeans. She was ordered to do community service and anger management.", fun_fact: "It wasn't an isolated incident. She has multiple assault charges involving phones, BlackBerries, and other objects thrown at staff." },
      { round_number: 4, round_label: "THE VILLAIN", question_text: "One of them played a Bond-adjacent villain \u2014 starring as the imposing Ludmilla Drago in Rocky IV and as the warrior Red Sonja in her own sword-and-sorcery film. Which one?", correct_answer: "b", explanation: "Brigitte Nielsen played Ludmilla in Rocky IV (1985) and starred in Red Sonja (1985) alongside Arnold Schwarzenegger. Both roles capitalized on her striking 6'1\" Amazonian presence.", fun_fact: "Red Sonja flopped so badly that Schwarzenegger later called it the worst film he ever made." },
      { round_number: 5, round_label: "THE WALK", question_text: "One of them has a runway walk so distinctive and powerful that designers have said it can make or break a fashion show. Versace once called her \"the greatest catwalk model of all time.\" Which one?", correct_answer: "a", explanation: "Naomi Campbell's runway walk is considered the gold standard in fashion. Her fierce, confident stride has defined runway culture for over three decades. Gianni Versace specifically designed shows around her presence.", fun_fact: "She has famously fallen on the runway twice in platform shoes \u2014 and turned both falls into iconic moments." },
      { round_number: 6, round_label: "THE DANISH", question_text: "One of them was born in Denmark, stood 6'1\", and used her towering physical presence to break into Hollywood as an action star in the 1980s. Which one?", correct_answer: "b", explanation: "Brigitte Nielsen was born in Rodovre, Denmark, in 1963. At 6'1\", she was taller than most leading men. She parlayed her striking appearance and Scandinavian accent into an 80s action career.", fun_fact: "Before acting, she was a model in Italy and Germany. Stallone spotted her in a magazine and cast her in Beverly Hills Cop II \u2014 before they even met." },
      { round_number: 7, round_label: "THE SOUTH LONDON", question_text: "One of them was born in Streatham, South London, and became one of the most famous faces on the planet \u2014 as famous for her temper as for her beauty. Which one?", correct_answer: "a", explanation: "Naomi Campbell was born in South London in 1970. She has been on over 500 magazine covers and has walked for every major fashion house. Her career has spanned four decades and shows no sign of stopping.", fun_fact: "She is as famous for her philanthropy \u2014 including work with Nelson Mandela's children's charity \u2014 as she is for throwing phones." }
    ]
  }
];

const combined = [...existing, ...batch8];
writeFileSync("content/deathmatch-matchups.json", JSON.stringify(combined, null, 2));
console.log(`Total matchups: ${combined.length}`);
console.log("Added:", batch8.map(m => m.slug).join(", "));
