import { readFileSync, writeFileSync } from "fs";

const existing = JSON.parse(readFileSync("content/deathmatch-matchups.json", "utf-8"));

const batch2 = [
  {
    slug: "pele-vs-maradona",
    fighter_a_name: "Pelé",
    fighter_b_name: "Diego Maradona",
    fighter_a_nickname: "O Rei",
    fighter_b_nickname: "El Pibe de Oro",
    tagline: "God's Hand vs The King's Feet",
    matchup_type: "rivalry",
    difficulty: 2,
    rounds: [
      { round_number: 1, round_label: "THE NAME", question_text: "One of them was named after American inventor Thomas Edison \u2014 his parents dropped the \"i\" from Edison. Which one?", correct_answer: "a", explanation: "Pel\u00e9 was born Edson Arantes do Nascimento. His parents named him after Thomas Edison but an error on the birth certificate changed the spelling.", fun_fact: "The nickname \"Pel\u00e9\" came from mispronouncing a favourite goalkeeper's name at school. He hated the nickname at first." },
      { round_number: 2, round_label: "THE MATCH", question_text: "In the span of four minutes during the 1986 World Cup, one of them scored both the most controversial goal AND the greatest goal in history \u2014 in the same match against England. Which one?", correct_answer: "b", explanation: "Maradona scored the \"Hand of God\" (punching the ball past the goalkeeper) and then the \"Goal of the Century\" (dribbling past 5 English players) in the same quarterfinal match on June 22, 1986.", fun_fact: "He said the first goal was scored \"a little with the head of Maradona and a little with the hand of God.\"" },
      { round_number: 3, round_label: "THE YOUNGEST", question_text: "One of them won the World Cup at age 17 \u2014 scoring twice in the final \u2014 becoming the youngest player to ever win the tournament. Which one?", correct_answer: "a", explanation: "Pel\u00e9 won the 1958 World Cup in Sweden at age 17, scoring two goals in the 5-2 final victory. He had started playing for Santos at 15 and for Brazil at 16.", fun_fact: "He scored a hat-trick in the semi-final against France. The world had never seen a 17-year-old do anything like it." },
      { round_number: 4, round_label: "THE CITY", question_text: "One of them single-handedly lifted a southern Italian club to its first-ever league title, becoming a god in Naples. Which one?", correct_answer: "b", explanation: "Maradona led Napoli to their first Scudetto in 1987 \u2014 a club from the poor south beating the wealthy northern giants. He won a second title in 1990.", fun_fact: "Over a million people celebrated in the streets of Naples. The city had never won anything before Maradona arrived." },
      { round_number: 5, round_label: "THE THREE", question_text: "One of them won three World Cups \u2014 the only player in history to do so. Which one?", correct_answer: "a", explanation: "Pel\u00e9 won the World Cup in 1958, 1962, and 1970. No other player has ever won three. He scored 12 goals in 14 World Cup matches across his career.", fun_fact: "The 1970 Brazil team is still widely considered the greatest football team ever assembled." },
      { round_number: 6, round_label: "THE SECOND ACT", question_text: "One of them came out of retirement at 34 to play for the New York Cosmos, sparking a soccer revolution in America. Which one?", correct_answer: "a", explanation: "Pel\u00e9 joined the New York Cosmos of the NASL in 1975, scoring 37 goals in 64 matches. His arrival put American soccer on the map.", fun_fact: "Before Pel\u00e9, American stadiums were empty for soccer. After him, attendance tripled across the league." },
      { round_number: 7, round_label: "THE FALL", question_text: "One of them was banned from football for 15 months after failing a drug test during the 1994 World Cup. Which one?", correct_answer: "b", explanation: "Maradona tested positive for ephedrine during the 1994 World Cup in the USA. He was expelled from the tournament and banned for 15 months. It was his last World Cup.", fun_fact: "His wild-eyed celebration after scoring against Greece in that tournament \u2014 screaming into a camera \u2014 became one of football's most iconic and haunting images." }
    ]
  },
  {
    slug: "madonna-vs-debbie-harry",
    fighter_a_name: "Madonna",
    fighter_b_name: "Debbie Harry",
    fighter_a_nickname: "The Material Girl",
    fighter_b_nickname: "The Punk Priestess",
    tagline: "Who Owned Downtown?",
    matchup_type: "rivalry",
    difficulty: 2,
    rounds: [
      { round_number: 1, round_label: "ORIGIN STORY", question_text: "One of them arrived in New York City with $35 in her pocket and became the best-selling female recording artist of all time. Which one?", correct_answer: "a", explanation: "Madonna moved to Manhattan in 1977 with $35, worked at Dunkin' Donuts and as a dancer. She went on to sell over 400 million records worldwide.", fun_fact: "She studied briefly with the Alvin Ailey American Dance Theater before switching to music." },
      { round_number: 2, round_label: "BEFORE THE MUSIC", question_text: "Before picking up a microphone, one of them worked as a Playboy Bunny waitress at New York's Playboy Club. Which one?", correct_answer: "b", explanation: "Debbie Harry worked as a Playboy Bunny at the New York Playboy Club from 1968 to 1973. She also waitressed at Max's Kansas City before co-founding Blondie in 1974.", fun_fact: "She also worked as a go-go dancer in a New Jersey discoth\u00e8que." },
      { round_number: 3, round_label: "THE FIRST", question_text: "One of them had the first number-one single in US history to feature rap vocals \u2014 in 1981, years before rap went mainstream. Which one?", correct_answer: "b", explanation: "Blondie's \"Rapture\" hit #1 on the Billboard Hot 100 on March 28, 1981. It was also the first rap video aired on MTV when the channel launched later that year.", fun_fact: "Debbie Harry name-checks graffiti artist Fab Five Freddy and DJ Grandmaster Flash in the rap verse." },
      { round_number: 4, round_label: "THE WEAPON", question_text: "One of them turned a cone-shaped bra designed by Jean Paul Gaultier into the most iconic costume in pop history. Which one?", correct_answer: "a", explanation: "Madonna debuted the pink satin cone bra on the Blond Ambition Tour in 1990. Gaultier originally designed the cone shape for his teddy bear before adapting it for her.", fun_fact: "The tour opened on April 13, 1990, in Chiba, Japan. The Vatican condemned it. Madonna didn't care." },
      { round_number: 5, round_label: "THE SCENE", question_text: "One of them was a regular at CBGB alongside the Ramones, Talking Heads, and Television \u2014 helping define New York punk. Which one?", correct_answer: "b", explanation: "Blondie was a CBGB house band from 1974, performing alongside the Ramones, Talking Heads, and Television. The club on the Bowery incubated the entire punk and new wave movement.", fun_fact: "Harry made CBGB's glamorous \u2014 she proved punk could have cheekbones." },
      { round_number: 6, round_label: "THE RECORD", question_text: "One of them has sold over 400 million records worldwide \u2014 more than any female artist in history, certified by Guinness. Which one?", correct_answer: "a", explanation: "Madonna was recertified by Guinness World Records in 2023 as the best-selling female recording artist of all time. Only The Beatles, Elvis, and Michael Jackson have sold more.", fun_fact: "She has had more #1 hits on the Billboard Dance Club chart than any artist in history \u2014 male or female." },
      { round_number: 7, round_label: "THE NAME", question_text: "One of them fronted a band whose name was also her nickname \u2014 and \"Heart of Glass\" made her the coolest blonde in New York. Which one?", correct_answer: "b", explanation: "Debbie Harry fronted Blondie \u2014 a name that doubled as her nickname. \"Heart of Glass\" (1979) became a worldwide #1 hit and crossed punk into disco territory.", fun_fact: "She hated when people called the band \"Blondie\" thinking it was just her. The T-shirts read \"Blondie is a group.\"" }
    ]
  },
  {
    slug: "elton-john-vs-freddie-mercury",
    fighter_a_name: "Elton John",
    fighter_b_name: "Freddie Mercury",
    fighter_a_nickname: "The Rocket Man",
    fighter_b_nickname: "The Voice",
    tagline: "Who Wore the Crown?",
    matchup_type: "crossover",
    difficulty: 2,
    rounds: [
      { round_number: 1, round_label: "THE NAME", question_text: "Both were born with very different names. One was born Reginald Kenneth Dwight. The other was born Farrokh Bulsara in Zanzibar. Who was Reginald?", correct_answer: "a", explanation: "Elton John was born Reginald Kenneth Dwight on March 25, 1947. He legally changed his name in 1972. Freddie Mercury was born Farrokh Bulsara in Zanzibar and adopted \"Freddie\" at boarding school in India.", fun_fact: "Mercury's classmates gave him the nickname because they couldn't pronounce Farrokh." },
      { round_number: 2, round_label: "THE PERFORMANCE", question_text: "One of them delivered what was voted the greatest live performance in rock history \u2014 a 21-minute set at Wembley in 1985 that included \"Bohemian Rhapsody\" and \"We Are the Champions.\" Which one?", correct_answer: "b", explanation: "Freddie Mercury and Queen's Live Aid performance on July 13, 1985, was voted the greatest live performance ever in a 2005 industry poll. His sustained \"Aaaaaay-o\" call-and-response became known as \"The Note Heard Round the World.\"", fun_fact: "The 72,000-strong Wembley crowd sang in perfect unison. The BBC called it \"the greatest display of community singing the old stadium had seen.\"" },
      { round_number: 3, round_label: "THE SINGLE", question_text: "One of them recorded the best-selling single since charts began \u2014 a tribute performed only once, at a funeral in Westminster Abbey watched by 2.5 billion people. Which one?", correct_answer: "a", explanation: "Elton John's \"Candle in the Wind 1997\" for Princess Diana's funeral is the highest-selling single since charts began in the 1950s. It sold 658,000 copies on its first day in the UK alone.", fun_fact: "He never performed the song publicly again after the funeral. Only Bing Crosby's \"White Christmas\" (1942) has sold more physical copies." },
      { round_number: 4, round_label: "THE VOICE", question_text: "Scientists studied one of their voices and found he could vibrate his vocal cords at roughly four times the speed of a typical singer, explaining his extraordinary power. Which one?", correct_answer: "b", explanation: "A 2016 study by Austrian, Czech, and Swedish researchers analyzed Mercury's voice and found his vocal cords vibrated with remarkable speed and irregularity, producing his unique timbre and power.", fun_fact: "Despite being known as a tenor, the researchers concluded he was actually a baritone who could sing in the tenor range." },
      { round_number: 5, round_label: "THE TITLE", question_text: "One of them was knighted by Queen Elizabeth II and became \"Sir\" \u2014 for services to music and charity. Which one?", correct_answer: "a", explanation: "Elton John was knighted in 1998, becoming Sir Elton Hercules John. He received the honor for his contributions to music and his charitable work, particularly around AIDS awareness.", fun_fact: "He is one of the few musicians to have achieved EGOT status \u2014 Emmy, Grammy, Oscar, and Tony." },
      { round_number: 6, round_label: "THE FOUNDATION", question_text: "After losing two friends to AIDS \u2014 including the other man in this matchup \u2014 one of them founded a charity that has raised over $600 million. Which one?", correct_answer: "a", explanation: "Elton John founded the Elton John AIDS Foundation in 1992 after losing Freddie Mercury and another close friend to AIDS within the same year. It has raised over $600 million.", fun_fact: "John was among 35 close friends at Mercury's funeral on November 27, 1991." },
      { round_number: 7, round_label: "THE FAREWELL", question_text: "One of them publicly confirmed his AIDS diagnosis only 24 hours before dying at age 45. Which one?", correct_answer: "b", explanation: "Freddie Mercury issued a public statement confirming his AIDS diagnosis on November 23, 1991. He died the following evening, November 24, at his home in Kensington.", fun_fact: "He had kept his diagnosis private for years. His final statement read: \"I felt it correct to keep this information private to protect the privacy of those around me.\"" }
    ]
  },
  {
    slug: "bruce-lee-vs-chuck-norris",
    fighter_a_name: "Bruce Lee",
    fighter_b_name: "Chuck Norris",
    fighter_a_nickname: "The Dragon",
    fighter_b_nickname: "The Legend",
    tagline: "Enter the Dragon vs Missing in Action",
    matchup_type: "franchise",
    difficulty: 2,
    rounds: [
      { round_number: 1, round_label: "THE FIGHT", question_text: "In Way of the Dragon (1972), these two fought inside the Roman Colosseum \u2014 the crew bribed officials and snuck in cameras because filming was illegal. Who won the fight on screen?", correct_answer: "a", explanation: "Bruce Lee's character defeats Chuck Norris's character Colt in the climactic fight. Lee personally choreographed every move. It is widely considered the greatest movie fight ever filmed.", fun_fact: "The two were friends in real life and trained together. Norris later joked that he only agreed because Lee promised him he'd look good losing." },
      { round_number: 2, round_label: "THE CHAMPION", question_text: "One of them was a real six-time Professional Middleweight Karate Champion with a competitive fight record of 65 wins and 5 losses. Which one?", correct_answer: "b", explanation: "Chuck Norris dominated professional karate tournaments from 1965 to 1970, winning virtually every major title including the World Professional Middleweight Championship.", fun_fact: "He compiled wins over champions Joe Lewis, Arnold Urquidez, and Skipper Mullins. He was the real deal." },
      { round_number: 3, round_label: "THE REJECTION", question_text: "One of them was rejected by Hollywood for being \"too Chinese\" \u2014 losing the lead role in Kung Fu to David Carradine. So he went to Hong Kong and became the biggest movie star on earth. Which one?", correct_answer: "a", explanation: "Bruce Lee was passed over for the role of Kwai Chang Caine in the TV series Kung Fu, which went to non-Asian actor David Carradine. Frustrated, Lee returned to Hong Kong and made history.", fun_fact: "His first Hong Kong film, The Big Boss, broke box office records across Asia. Hollywood came crawling back." },
      { round_number: 4, round_label: "THE MEME", question_text: "One of them became the internet's first major meme \u2014 absurd \"facts\" about his invincibility started on forums in 2005 and spread worldwide. Which one?", correct_answer: "b", explanation: "Chuck Norris Facts originated on Something Awful forums in 2005, initially about Vin Diesel before switching to Norris. A high school student named Ian Spector built a generator site that drew 10,000 users overnight.", fun_fact: "Norris embraced it completely. He said his personal favourite was: \"They once tried to carve Chuck Norris's face into Mount Rushmore. The granite wasn't hard enough.\"" },
      { round_number: 5, round_label: "THE PHILOSOPHY", question_text: "One of them rejected all classical martial arts styles and created his own philosophy called Jeet Kune Do \u2014 \"The Way of the Intercepting Fist.\" Which one?", correct_answer: "a", explanation: "Bruce Lee studied Wing Chun, boxing, fencing, and other arts, then rejected rigid styles in favor of taking what works from each. Jeet Kune Do was his personal martial arts philosophy, not a fixed system.", fun_fact: "He said: \"Absorb what is useful, discard what is useless, and add what is specifically your own.\"" },
      { round_number: 6, round_label: "THE BROTHER", question_text: "One of them dedicated his Missing in Action film trilogy to his younger brother, who was killed in Vietnam while serving in the 101st Airborne Division. Which one?", correct_answer: "b", explanation: "Chuck Norris's brother Wieland was a private in the 101st Airborne, killed in June 1970 while on patrol near Firebase Ripcord in Vietnam. The Missing in Action films (1984-1988) were his tribute.", fun_fact: "Norris served in the US Air Force before becoming a martial artist. Military service ran in the family." },
      { round_number: 7, round_label: "THE LEGACY", question_text: "One of them died at 32, and his most famous film was released six days after his death. Which one?", correct_answer: "a", explanation: "Bruce Lee died on July 20, 1973, in Hong Kong at age 32 from cerebral edema. Enter the Dragon premiered on July 26, 1973 \u2014 six days later \u2014 and became a global phenomenon.", fun_fact: "He once said: \"The key to immortality is first living a life worth remembering.\" He was right." }
    ]
  },
  {
    slug: "becker-vs-agassi",
    fighter_a_name: "Boris Becker",
    fighter_b_name: "Andre Agassi",
    fighter_a_nickname: "Boom Boom",
    fighter_b_nickname: "The Rebel",
    tagline: "The Brat vs The Rebel",
    matchup_type: "rivalry",
    difficulty: 2,
    rounds: [
      { round_number: 1, round_label: "THE YOUNGEST", question_text: "One of them won Wimbledon at 17 \u2014 the youngest men's singles champion in the tournament's history, and he was completely unseeded. Which one?", correct_answer: "a", explanation: "Boris Becker won Wimbledon in 1985 at 17 years and 7 months, beating Kevin Curren in four sets. He was the first unseeded player and the first German to win the title.", fun_fact: "His diving volleys became his trademark \u2014 the press dubbed his acrobatic playing style \"Becker's Boing.\"" },
      { round_number: 2, round_label: "THE SLOGAN", question_text: "One of them starred in a camera commercial with the tagline \"Image is everything\" \u2014 a phrase that haunted him for years because critics said he was all style and no substance. Which one?", correct_answer: "b", explanation: "Andre Agassi filmed the Canon Rebel camera ad in the Nevada desert, stepping out of a white Lamborghini and uttering the infamous line. It took three more years before he won his first Grand Slam.", fun_fact: "He later called it the worst career decision he ever made. His autobiography \"Open\" was partly a response to the \"image\" label." },
      { round_number: 3, round_label: "THE SECRET", question_text: "One of them wore a wig held together with pins during a Grand Slam final \u2014 and later said the fear of it falling off cost him the match. Which one?", correct_answer: "b", explanation: "Agassi wore a hairpiece in the 1990 French Open final against Andres Gomez. He spent the entire match terrified it would fall apart on live television. He lost. He revealed the secret in his 2009 autobiography.", fun_fact: "His flowing lion-mane hair of the early 90s \u2014 one of the most iconic looks in sports \u2014 was completely fake." },
      { round_number: 4, round_label: "THE FALL", question_text: "One of them was sentenced to two and a half years in a British prison for hiding \u00a32.5 million in assets during bankruptcy proceedings. Which one?", correct_answer: "a", explanation: "Boris Becker was sentenced in April 2022 for concealing assets during bankruptcy. He served eight months before being released and deported to Germany under a fast-track scheme for foreign prisoners.", fun_fact: "The judge noted his 2002 suspended sentence for tax evasion in Germany as an aggravating factor \u2014 he hadn't learned." },
      { round_number: 5, round_label: "THE GOLDEN SLAM", question_text: "One of them is the first male tennis player in history to win all four Grand Slam titles plus an Olympic gold medal across his career. Which one?", correct_answer: "b", explanation: "Agassi completed the Career Golden Slam by winning the 1999 French Open \u2014 the only Grand Slam he was missing. Combined with his 1996 Olympic gold in Atlanta, he achieved what no man had done before.", fun_fact: "He won 8 Grand Slam titles total: 4 Australian Opens, 2 US Opens, 1 Wimbledon, 1 French Open." },
      { round_number: 6, round_label: "THE POWER COUPLE", question_text: "One of them married the greatest female tennis player of all time \u2014 together they hold more Grand Slam singles titles than any couple in history. Which one?", correct_answer: "b", explanation: "Andre Agassi married Steffi Graf in October 2001. Between them they hold 30 Grand Slam singles titles (his 8 + her 22). They are still married and live in Las Vegas.", fun_fact: "They started dating after both won the French Open in 1999. She had also completed a Calendar Year Golden Slam in 1988 \u2014 the only player ever to do so." },
      { round_number: 7, round_label: "THE TOTAL", question_text: "One of them won 6 Grand Slam titles, including three Wimbledons. The other won 8. Who won 6?", correct_answer: "a", explanation: "Becker won 6 Grand Slam singles titles: Wimbledon (1985, 1986, 1989), Australian Open (1991, 1996), and US Open (1989). Agassi won 8 across all four majors.", fun_fact: "Despite fewer titles, Becker reached 7 Wimbledon finals \u2014 the tournament was his kingdom." }
    ]
  }
];

const combined = [...existing, ...batch2];
writeFileSync("content/deathmatch-matchups.json", JSON.stringify(combined, null, 2));
console.log(`Total matchups: ${combined.length}`);
console.log("Added:", batch2.map(m => m.slug).join(", "));
