import { readFileSync, writeFileSync } from "fs";

const existing = JSON.parse(readFileSync("content/deathmatch-matchups.json", "utf-8"));

const batch6 = [
  {
    slug: "wham-vs-bee-gees",
    fighter_a_name: "Wham!",
    fighter_b_name: "Bee Gees",
    fighter_a_nickname: "The Pop Princes",
    fighter_b_nickname: "The Brothers Gibb",
    tagline: "Disco Falsetto vs Pop Falsetto",
    matchup_type: "era",
    difficulty: 2,
    rounds: [
      { round_number: 1, round_label: "THE SOUNDTRACK", question_text: "One of these groups recorded the soundtrack to a 1977 film that sold over 40 million copies \u2014 making it one of the best-selling albums of all time. Which one?", correct_answer: "b", explanation: "The Bee Gees wrote and performed the Saturday Night Fever soundtrack, which sold over 40 million copies worldwide. It defined the disco era and turned them into global superstars.", fun_fact: "The soundtrack contains five #1 singles. It spent 24 consecutive weeks at #1 on the Billboard 200." },
      { round_number: 2, round_label: "THE WALL", question_text: "One of these groups was the first Western pop act to perform in communist China \u2014 their manager spent 18 months bribing officials to make it happen. Which one?", correct_answer: "a", explanation: "Wham! performed in Beijing and Guangzhou in April 1985, becoming the first Western pop group to play in the People's Republic of China. Manager Simon Napier-Bell spent months negotiating with Chinese officials.", fun_fact: "The Chinese audience sat in confused silence for much of the show. They had never seen anything like it." },
      { round_number: 3, round_label: "THE CHRISTMAS", question_text: "One of these groups released a Christmas single that took 36 years to reach #1 in the UK \u2014 finally topping the chart in 2021. Which one?", correct_answer: "a", explanation: "Wham!'s \"Last Christmas\" was released in 1984 but was kept off #1 by Band Aid's \"Do They Know It's Christmas.\" It finally reached #1 on New Year's Day 2021 and became Christmas #1 in 2023.", fun_fact: "It is now the third best-selling UK single of all time with 5.34 million combined sales." },
      { round_number: 4, round_label: "THE CPR", question_text: "One of these groups recorded a song whose tempo (103 BPM) is now used worldwide to train people how to perform CPR at the correct chest compression rate. Which one?", correct_answer: "b", explanation: "The Bee Gees' \"Stayin' Alive\" has a tempo of approximately 103 beats per minute \u2014 matching the ideal rate of 100-120 chest compressions per minute recommended for CPR.", fun_fact: "Medical studies confirmed that people who hum \"Stayin' Alive\" while performing CPR maintain better compression rates. The song is literally saving lives." },
      { round_number: 5, round_label: "THE GHOSTWRITERS", question_text: "One of these groups secretly wrote hit songs for other artists \u2014 including Barbra Streisand's \"Woman in Love\" and Dionne Warwick's \"Heartbreaker.\" Which one?", correct_answer: "b", explanation: "The Bee Gees (primarily Barry Gibb) wrote songs for numerous other artists. Barry Gibb wrote Streisand's \"Woman in Love\" (#1 worldwide) and co-produced her Guilty album, which sold 20 million copies.", fun_fact: "They also wrote \"Islands in the Stream\" for Kenny Rogers and Dolly Parton, and \"Chain Reaction\" for Diana Ross." },
      { round_number: 6, round_label: "THE NOTE", question_text: "One of these groups was written by a member who got the idea from a misspelled note on a bedroom door: \"Wake me up up before you go go.\" Which one?", correct_answer: "a", explanation: "Andrew Ridgeley left a note on his bedroom door for his parents that accidentally read \"Wake me up up before you go go.\" George Michael saw it, laughed, and turned it into one of the biggest pop hits of the 1980s.", fun_fact: "The song hit #1 in both the US and UK. The music video's neon colors and \"Choose Life\" t-shirts defined 1984." },
      { round_number: 7, round_label: "THE SURVIVORS", question_text: "One of these groups lost three of its members \u2014 leaving only one surviving brother from the original lineup. Which one?", correct_answer: "b", explanation: "Three of the four Gibb brothers have died: Andy (1988, age 30), Maurice (2003, age 53), and Robin (2012, age 62). Barry Gibb, now in his late 70s, is the sole surviving brother.", fun_fact: "Wham! lost George Michael on Christmas Day 2016 at age 53. Andrew Ridgeley is still alive." }
    ]
  },
  {
    slug: "pacino-vs-hoffman",
    fighter_a_name: "Al Pacino",
    fighter_b_name: "Dustin Hoffman",
    fighter_a_nickname: "Scarface",
    fighter_b_nickname: "The Graduate",
    tagline: "Scarface vs The Graduate",
    matchup_type: "rivalry",
    difficulty: 2,
    rounds: [
      { round_number: 1, round_label: "THE SCHOOL", question_text: "Both studied method acting under Lee Strasberg at the same legendary institution. One of them stayed awake for three days straight to play a sleep-deprived character in Marathon Man. Which one?", correct_answer: "b", explanation: "Dustin Hoffman famously stayed awake for days to capture the exhaustion of his character in Marathon Man (1976). His co-star Laurence Olivier reportedly said: \"My dear boy, why don't you just try acting?\"", fun_fact: "Both Pacino and Hoffman studied at the Actors Studio under Strasberg. They represent two sides of the same method." },
      { round_number: 2, round_label: "THE FAMILY", question_text: "One of them played Michael Corleone \u2014 a role that defined the modern gangster film and earned him his first Oscar nomination at age 32. Which one?", correct_answer: "a", explanation: "Al Pacino played Michael Corleone in The Godfather (1972) and The Godfather Part II (1974). He was nominated for Best Supporting Actor for the first film and Best Actor for the sequel.", fun_fact: "Every major studio wanted Robert Redford for the role. Director Francis Ford Coppola fought to cast the unknown Pacino." },
      { round_number: 3, round_label: "THE DRESS", question_text: "One of them played a man who disguises himself as a woman to land an acting role \u2014 a comedy that earned 10 Oscar nominations. Which one?", correct_answer: "b", explanation: "Dustin Hoffman starred as Michael Dorsey / Dorothy Michaels in Tootsie (1982). The film received 10 Academy Award nominations and is considered one of the greatest comedies ever made.", fun_fact: "Hoffman later said the role changed how he understood women: \"I think I'm an interesting woman... and I know that if I met myself at a party, I would never talk to that character.\"" },
      { round_number: 4, round_label: "THE WAIT", question_text: "One of them was nominated for the Oscar eight times before finally winning \u2014 the longest losing streak for an actor who eventually won. Which one?", correct_answer: "a", explanation: "Al Pacino was nominated eight times (starting with The Godfather in 1973) before winning Best Actor for Scent of a Woman in 1993 \u2014 a 20-year wait.", fun_fact: "Many consider Scent of a Woman one of his weaker performances. The Academy was making up for lost time." },
      { round_number: 5, round_label: "THE DOUBLE", question_text: "One of them won two Best Actor Oscars \u2014 for Kramer vs. Kramer and Rain Man. Which one?", correct_answer: "b", explanation: "Dustin Hoffman won Best Actor for Kramer vs. Kramer (1979) and Rain Man (1988). His portrayal of autistic savant Raymond Babbitt in Rain Man became one of the most studied performances in acting history.", fun_fact: "He has seven total Oscar nominations. Pacino has nine." },
      { round_number: 6, round_label: "THE SAY HELLO", question_text: "One of them delivered the line \"Say hello to my little friend\" before unleashing a grenade launcher in a film that flopped at release but became a cultural monument. Which one?", correct_answer: "a", explanation: "Al Pacino as Tony Montana in Scarface (1983). The film was a box office disappointment and critically savaged, but became one of the most quoted and referenced films in hip-hop and pop culture.", fun_fact: "Pacino said Scarface is the film he most wished he'd been Oscar-nominated for." },
      { round_number: 7, round_label: "THE BREAKTHROUGH", question_text: "One of them was 30 years old and unknown when he was cast as a 21-year-old college graduate seduced by an older woman \u2014 launching his career overnight. Which one?", correct_answer: "b", explanation: "Dustin Hoffman was 30 when he starred as Benjamin Braddock in The Graduate (1967). He was cast despite being nearly a decade older than the character. The film made him an instant star.", fun_fact: "He earned $17,000 for The Graduate. The film grossed $104 million." }
    ]
  },
  {
    slug: "travolta-vs-eastwood",
    fighter_a_name: "John Travolta",
    fighter_b_name: "Clint Eastwood",
    fighter_a_nickname: "The Dancer",
    fighter_b_nickname: "The Man With No Name",
    tagline: "The Dance vs The Stare",
    matchup_type: "crossover",
    difficulty: 2,
    rounds: [
      { round_number: 1, round_label: "THE SUIT", question_text: "One of them made the white disco suit iconic \u2014 a single outfit that defined an entire decade's nightlife. Which one?", correct_answer: "a", explanation: "John Travolta's white three-piece suit in Saturday Night Fever (1977) became the most recognizable outfit in disco history. The suit sold at auction for $145,000 in 1995.", fun_fact: "He was only 23 when he filmed it. The dance sequences were largely improvised." },
      { round_number: 2, round_label: "THE LINE", question_text: "One of them delivered \"Go ahead, make my day\" \u2014 a line so famous that President Reagan quoted it in a speech to Congress. Which one?", correct_answer: "b", explanation: "Clint Eastwood as Dirty Harry in Sudden Impact (1983). Reagan used the line in a 1985 tax policy speech, cementing it in American political culture.", fun_fact: "The line was written by screenwriter Charles B. Pierce, not Eastwood. But nobody remembers that." },
      { round_number: 3, round_label: "THE COMEBACK", question_text: "One of them had the greatest career comeback in Hollywood history when Quentin Tarantino cast him in a 1994 film after years in straight-to-video obscurity. Which one?", correct_answer: "a", explanation: "John Travolta's career had flatlined before Quentin Tarantino cast him as Vincent Vega in Pulp Fiction (1994). The role earned him his second Oscar nomination and relaunched his career overnight.", fun_fact: "Tarantino wrote the part specifically for Travolta. Nobody else was ever considered." },
      { round_number: 4, round_label: "THE DIRECTOR", question_text: "One of them won the Academy Award for Best Director twice \u2014 for a revisionist Western and a boxing drama. Which one?", correct_answer: "b", explanation: "Clint Eastwood won Best Director for Unforgiven (1992) and Million Dollar Baby (2004). Unforgiven also won Best Picture, making him one of the few actor-directors to achieve the double.", fun_fact: "He has directed over 40 films. He shoots fast, rarely does more than two takes, and finishes under budget." },
      { round_number: 5, round_label: "THE RELIGION", question_text: "One of them has been one of the most prominent members of Scientology since 1975, crediting the church with saving his life. Which one?", correct_answer: "a", explanation: "John Travolta joined Scientology in 1975 and has been one of the church's most visible celebrity members for nearly 50 years. He starred in the Scientology-backed film Battlefield Earth (2000), widely considered one of the worst films ever made.", fun_fact: "He once said Scientology \"has better tools than Catholicism.\"" },
      { round_number: 6, round_label: "THE AGE", question_text: "One of them directed a critically acclaimed film at age 84, continuing to work into his 90s \u2014 one of the longest active careers in Hollywood history. Which one?", correct_answer: "b", explanation: "Clint Eastwood directed Cry Macho at age 91 and Juror #2 at age 94. His career spans from the 1950s TV show Rawhide to the 2020s \u2014 over seven decades of continuous work.", fun_fact: "He was already 62 when he won his first Oscar. Most actors retire by that age." },
      { round_number: 7, round_label: "THE CHEESE", question_text: "One of them ordered a \"Royale with Cheese\" in a scene that became one of the most quoted dialogues in film history. Which one?", correct_answer: "a", explanation: "John Travolta as Vincent Vega discusses the metric system and European fast food with Samuel L. Jackson in Pulp Fiction. The \"Royale with Cheese\" exchange is endlessly quoted.", fun_fact: "Tarantino wrote the scene based on a real conversation. In Paris, McDonald's really does call it a Royal Cheese." }
    ]
  },
  {
    slug: "cher-vs-tina-turner",
    fighter_a_name: "Cher",
    fighter_b_name: "Tina Turner",
    fighter_a_nickname: "The Goddess of Pop",
    fighter_b_nickname: "The Queen of Rock",
    tagline: "Survivor vs Survivor",
    matchup_type: "rivalry",
    difficulty: 2,
    rounds: [
      { round_number: 1, round_label: "THE ESCAPE", question_text: "One of them escaped an abusive marriage that included broken bones, burned skin, and rapes \u2014 then rebuilt her career from scratch and became bigger than ever. Which one?", correct_answer: "b", explanation: "Tina Turner left Ike Turner in 1976 after years of documented physical and sexual abuse. Her 1986 autobiography I, Tina detailed the horrors. She rebuilt from nightclub acts to arena tours.", fun_fact: "She left with 36 cents and a Mobil credit card. Within a decade she was selling out stadiums worldwide." },
      { round_number: 2, round_label: "THE OSCAR", question_text: "One of them won the Academy Award for Best Actress \u2014 proving she was more than a singer. Which one?", correct_answer: "a", explanation: "Cher won the Oscar for Best Actress for Moonstruck in 1988. She had previously been dismissed by Hollywood as \"just a pop star\" and showed up to the ceremony in a famously outrageous outfit.", fun_fact: "When she won, she said: \"I don't think this means I'm somebody... but I guess I'm on my way.\"" },
      { round_number: 3, round_label: "THE EFFECT", question_text: "One of them released a 1998 hit that pioneered the use of Auto-Tune as a creative vocal effect \u2014 changing pop music production forever. The technique was named after her. Which one?", correct_answer: "a", explanation: "Cher's \"Believe\" (1998) was the first hit to use Auto-Tune as a deliberate vocal distortion effect. Producers initially tried to keep the technique secret. It became known as the \"Cher Effect.\"", fun_fact: "She was 52 when the song hit #1 worldwide. It revitalized a career that was already four decades long." },
      { round_number: 4, round_label: "THE COMEBACK ALBUM", question_text: "One of them released Private Dancer in 1984 \u2014 a comeback album that sold over 20 million copies and proved the greatest second act in music history. Which one?", correct_answer: "b", explanation: "Tina Turner's Private Dancer (1984) went 5x platinum in the US alone. It featured \"What's Love Got to Do with It\" \u2014 her first and only solo #1 on the Billboard Hot 100.", fun_fact: "She was 44 years old. The music industry had written her off. She outsold every female artist that year." },
      { round_number: 5, round_label: "THE SONNY", question_text: "One of them was part of a married performing duo in the 1960s-70s that had their own TV variety show. Which one?", correct_answer: "a", explanation: "Cher performed with husband Sonny Bono as Sonny & Cher. Their TV show The Sonny & Cher Comedy Hour ran from 1971-1974 on CBS. They divorced in 1975.", fun_fact: "Sonny Bono later became mayor of Palm Springs and a US Congressman. He died in a skiing accident in 1998." },
      { round_number: 6, round_label: "THE FAREWELL", question_text: "One of them holds the record for the longest-running farewell tour in music history \u2014 a \"farewell\" that lasted three years. Which one?", correct_answer: "a", explanation: "Cher's Living Proof: The Farewell Tour ran from 2002 to 2005, grossing over $250 million. She then came out of \"retirement\" and launched a Las Vegas residency. She's still performing.", fun_fact: "Tina Turner's actual farewell was more final. Her Tina!: 50th Anniversary Tour (2008-2009) was her last. She died in May 2023." },
      { round_number: 7, round_label: "THE LEGS", question_text: "One of them was as famous for her legs as for her voice \u2014 performing in miniature skirts and heels well into her 70s, with the most famous legs in rock and roll. Which one?", correct_answer: "b", explanation: "Tina Turner's legs became an inseparable part of her brand. She performed in high heels and short skirts throughout her career, and her legs were reportedly insured for $3.2 million.", fun_fact: "She once said: \"My legacy is that I stayed on course from the beginning to the end, because I believed in something inside of me.\"" }
    ]
  },
  {
    slug: "murphy-vs-belushi",
    fighter_a_name: "Eddie Murphy",
    fighter_b_name: "John Belushi",
    fighter_a_nickname: "The King of Comedy",
    fighter_b_nickname: "The Animal",
    tagline: "Saturday Night Legends",
    matchup_type: "crossover",
    difficulty: 2,
    rounds: [
      { round_number: 1, round_label: "THE AGE", question_text: "One of them joined the Saturday Night Live cast at just 19 years old \u2014 and single-handedly saved the show from cancellation with his performances. Which one?", correct_answer: "a", explanation: "Eddie Murphy joined SNL in 1980 at age 19. The show was struggling after the original cast left, and Murphy's characters (Gumby, Buckwheat, Mr. Robinson) revived it.", fun_fact: "He was initially hired as an extra/featured player. Within weeks he was the breakout star." },
      { round_number: 2, round_label: "THE BLUES", question_text: "One of them co-created a fictional blues band for SNL that became so popular it spawned a #1 album and a hit movie. Which one?", correct_answer: "b", explanation: "John Belushi and Dan Aykroyd created The Blues Brothers for SNL. The 1980 film became a cult classic, and the Briefcase Full of Blues album reached #1 on the Billboard 200 in 1978.", fun_fact: "The Blues Brothers film holds the record for most cars destroyed in a movie \u2014 over 100." },
      { round_number: 3, round_label: "THE BOX OFFICE", question_text: "One of them starred in Beverly Hills Cop (1984) \u2014 the highest-grossing film of that year \u2014 and 48 Hrs., Trading Places, and Coming to America in the span of six years. Which one?", correct_answer: "a", explanation: "Eddie Murphy dominated 1980s box offices. Beverly Hills Cop grossed $316 million worldwide. Between 1982 and 1988, he starred in five consecutive box office hits.", fun_fact: "He was offered the role of Winston in Ghostbusters (1984) but turned it down. The role went to Errol Hudson." },
      { round_number: 4, round_label: "THE TOGA", question_text: "One of them starred in Animal House (1978) \u2014 a college comedy so successful that toga parties became a nationwide phenomenon. Which one?", correct_answer: "b", explanation: "John Belushi played Bluto Blutarsky in National Lampoon's Animal House. The film grossed $141 million on a $2.8 million budget and invented the modern gross-out comedy genre.", fun_fact: "Belushi's food fight scene and \"Was it over when the Germans bombed Pearl Harbor?\" speech were largely improvised." },
      { round_number: 5, round_label: "THE VOICES", question_text: "One of them voiced Donkey in the Shrek franchise and Mushu in Mulan \u2014 becoming one of the most successful voice actors in animation history. Which one?", correct_answer: "a", explanation: "Eddie Murphy voiced Donkey in all four Shrek films (2001-2010) and the dragon Mushu in Mulan (1998). The Shrek franchise grossed over $3.5 billion worldwide.", fun_fact: "He was the first actor to have two films open at #1 in the same weekend: Shrek 2 and Daddy Day Care were both in theaters simultaneously." },
      { round_number: 6, round_label: "THE CHATEAU", question_text: "One of them died at the Chateau Marmont hotel on the Sunset Strip at age 33 \u2014 from a lethal injection of heroin and cocaine administered by a companion. Which one?", correct_answer: "b", explanation: "John Belushi died on March 5, 1982, at the Chateau Marmont in Los Angeles. His companion Cathy Smith later pleaded guilty to administering the fatal \"speedball\" injection.", fun_fact: "He had been partying with Robin Williams and Robert De Niro earlier that evening. Both left before the fatal dose." },
      { round_number: 7, round_label: "THE RETURN", question_text: "One of them made a triumphant return to SNL in 2019 after 35 years away \u2014 hosting for the first time since leaving the show and winning an Emmy for the episode. Which one?", correct_answer: "a", explanation: "Eddie Murphy hosted SNL on December 21, 2019, his first time back since 1984. He revived his classic characters and won the Primetime Emmy for Outstanding Guest Actor in a Comedy Series.", fun_fact: "Belushi never got a second act. Murphy got dozens. That's the difference 33 years of life makes." }
    ]
  }
];

const combined = [...existing, ...batch6];
writeFileSync("content/deathmatch-matchups.json", JSON.stringify(combined, null, 2));
console.log(`Total matchups: ${combined.length}`);
console.log("Added:", batch6.map(m => m.slug).join(", "));
